### ISSUE TITLE
Support uses-permission-sdk-23

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#154]
Currently we've not supported `uses-permission-sdk-23` so it would be better to add an option to define whether one permission is for up to 23 or not.

ref: https://twitter.com/izumin5210/status/735289425324695552

**Comment by romshiri** [comment]
Hi @hotchemi , can you elaborate more on this issue?
Does it mean you can't add this kind of permission so only newer versions (Android 6.0 and above) will requested to grant this permission?

**Comment by hotchemi** [comment]
@romshiri Sorry for the late. Currently uses-permission-sdk-23 is treated as not granted if you support less than 23 api level. It means you gotta treat all permissions as just `uses-permission`.
So this enhancement will solve that.

**Comment by brianchu** [comment]
I am little confused of what this open issue status is. So no contribution welcomed but it is still open? And just to confirm: when app support <23 and running os level < 23, it will always treat as not granted? What about running in os level >= 23? Will the app always not granted? I want to contribute.

**Comment by hotchemi** [comment]
@brianchu this issue is not for contributors(we need to consider the spec) so could you try to tackle `contributionwelcome`? Thx!
https://github.com/permissions-dispatcher/PermissionsDispatcher/labels/contributionwelcome

**Comment by hotchemi** [comment]
not so many ppl has requested the feature..let me close :trollface:
