### ISSUE TITLE
Separate annotation and util module

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#27]
Like that.
https://github.com/MichaelEvans/Aftermath

**Comment by aurae** [comment]
We already have a setup like that, kind of, since the library module contains two source folders for `android` and plain `java`. What would be the advantage of this?

**Comment by hotchemi** [comment]
Nothing especially but when I tried to do that, it didn't go well may be...

**Comment by hotchemi** [comment]
It's worth to re-challenge.

**Comment by hotchemi** [comment]
This issue includes writing unit test for `PermissionUtis` with Robolectric and mockito.

**Comment by hotchemi** [comment]
too old
