### ISSUE TITLE
Android Lint failed with Kotlin 1.1.3, Activity/Fragment written by Java

### ISSUE THREAD

**Issue by ryugoo** [permissions-dispatcher/PermissionsDispatcher#331]
## Overview

- Android Lint failed with Kotlin 1.1.3
- It seems that "NeedOnRequestPermissionsResult" check does not work properly in Activity or Fragment written in Java

### Expected

- Lint is working correctly

### Actual

- Lint is not working correctly

## Environment

- PermissionsDispatcher 2.4.0
- Kotlin 1.1.3

## Reproducible steps

I wrote sample project.
https://github.com/ryugoo/PDKT113

**Comment by hotchemi** [comment]
@ryugoo we're so thankful for your report.
Though not sure it's our fault let me investigate with your sample and try to fix if needed 🙇 
cc: @shiraji

**Comment by shiraji** [comment]
If you change the version, you won't see the error.

```diff
-  ext.kotlin_version = '1.1.3'
+  ext.kotlin_version = '1.1.2-3'
```

Also, when I removed kotlin dependencies, I didn't see the error.
Since `annotationProcessor` has the different behavior with kapt, I concluded this is the problem with kapt v1.1.3.

I think you need to report this to kotlin's [issue tracker](https://youtrack.jetbrains.com/issues/KT).

**Comment by ryugoo** [comment]
@hotchemi @shiraji
Thank you for investigating!
I'm going to reporting issues to Kotlin's issue tracker.

**Comment by hotchemi** [comment]
I heard they started providing incremental build from 1.1.3 and I suppose it causes the problem.
But anyway it's so interesting and thx for your report!

**Comment by ryugoo** [comment]
I reported to Kotlin Issue tracker!
https://youtrack.jetbrains.com/issue/KT-18686

I wait some action on the place.
Thank you for interesting discussion!
I close this issue:)

**Comment by hotchemi** [comment]
@ryugoo thank you! we'll keep en eye on it!

**Comment by aurae** [comment]
Regarding the development in #350, we should check if the erroneous behaviour in Kotlin 1.1.3 is still present in the current stable release, 1.1.4-2. Since we require other enhancements in that version, it would be nice if this issue didn't block the upgrade.

**Comment by aurae** [comment]
Update: This still occurs with `1.1.4-2`. I noticed that we haven't updated our Lint rules to use the new UAST-based API yet, whose main selling point was Kotlin interoperability. I suppose that might help our case.

**Comment by aurae** [comment]
We will track progress on this in #359
