### ISSUE TITLE
Remove requirement for "kotlin = true"

### ISSUE THREAD

**Issue by aurae** [permissions-dispatcher/PermissionsDispatcher#350]
As discussed before, we might not have to force users to indicate the language of their annotated `@RuntimePermissions` class with `kotlin = true`. Taking a hint from how the [JUnit 5 team solves this issue](https://github.com/junit-team/junit5/issues/991), we might also be able to detect a Kotlin class by looking at its annotations during the annotation processor phase.

I'll play around with this a little and see if I can produce some results. Would be great to remove this additional step for our Kotlin-based users!

**Comment by hotchemi** [comment]
Thx! obviously a way to go!

**Comment by aurae** [comment]
It seems like the annotation processor doesn't receive the "proper" class when processing the Round Environment with kapt. Unfortunately, we can't detect `kotlin.Metadata`:

```kotlin
roundEnv.getElementsAnnotatedWith(RuntimePermissions::class.java)
    .sortedBy { it.simpleName.toString() }
    .forEach {
        val rpe = RuntimePermissionsElement(it as TypeElement)
        messager.printMessage(Diagnostic.Kind.WARNING, "RuntimePermissions Element: $it")
        messager.printMessage(Diagnostic.Kind.WARNING, "* Annotation Mirrors: ${it.annotationMirrors} (${it.annotationMirrors.size})")

        val metadataCls : Class<Annotation> = Class.forName("kotlin.Metadata") as Class<Annotation>
        messager.printMessage(Diagnostic.Kind.WARNING, "* Metadata Class: $metadataCls")
        messager.printMessage(Diagnostic.Kind.WARNING, "* Metadata On Cls: ${it.getAnnotation(metadataCls)}")
    }
```

```
Output:

w: warning: RuntimePermissions Element: permissions.dispatcher.samplekotlin.MainActivity
w: warning: * Annotation Mirrors: @permissions.dispatcher.RuntimePermissions(kotlin=true) (1)
w: warning: * Metadata Class: interface kotlin.Metadata
w: warning: * Metadata On Cls: null
```

Do you guys suppose we should raise an issue & ask about this for annotation processing specifically?

**Comment by hotchemi** [comment]
@aurae Sorry for the late! Thank you for your investigation and I suppose it's worth to file an issue to improve Kotlin dealing from APT!
I found similar forum thread but there's no response yet... 🤔 
https://discuss.kotlinlang.org/t/kotlin-data-classes-inspection-from-annotation-processor/2163

**Comment by hotchemi** [comment]
seems there's no way to detect annotated class is Kotlin or not within ATP... 😢 
@shiraji any idea?

**Comment by aurae** [comment]
To recap from the meeting: If the distinction between Java and Kotlin can't be made on a per-class basis, it should be moved "a level higher", and converted into a question of "kapt vs. javac apt". Because we are able to [detect kapt during the annotation processor's runtime](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/76c1026512d4388920e89f9f61d20f5c82059db2/processor/src/main/kotlin/permissions/dispatcher/processor/PermissionsProcessor.kt#L69), we can go the Kotlin route for *all* annotated classes in this case, modelling the interoperability with Java accordingly (e.g. using `@file:JvmName`). The last dealbreaker with this approach still remains the lack of a Kotlin version to [Google's compile-testing library](https://github.com/google/compile-testing), with which we can validate the correct behaviour during unit testing. We should be reaching out to JetBrains & ask for the plans for a library like that.

**Comment by hotchemi** [comment]
Thx for recapping!
Actually that's so so clever way and I'd like to go with it! So next step is I guess:

- Fix generated file template to allow Java to call its methods easily
- Create PR

As for unit testing, I've not investigated deeply but I wonder we can do file-base testing with google/compiler-testing like [that](https://github.com/google/auto/blob/e8b60d7c6609365d1b57ec3ebea29817d5e5ada9/service/src/test/java/com/google/auto/service/processor/AutoServiceProcessorTest.java#L46) at least they test manifest file generation in google/auto 📝

**Comment by jmatsu** [comment]
After upgrading Kotlin to 1.1.3, I confirmed a processor could see `kotlin.Metadata` by the same way https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/350#issuecomment-319587938 described.
Though it seems that you already got a conclusion of this discussion.... this is just for information!

**Comment by hotchemi** [comment]
@jmatsu Wow!!!

**Comment by aurae** [comment]
Really? I'm pretty sure I tested it on `1.1.4-2` and it wouldn't show up. Thanks for the info!

**Comment by aurae** [comment]
I've started work on the migration to `@kotlin.Metadata` [here](https://github.com/aurae/PermissionsDispatcher/tree/350_kotlin).

**Comment by hotchemi** [comment]
@aurae as for lint issue actually I'm not sure it was addressed already or not(seems no update on youtrack?). But please give it a go!

**Comment by shiraji** [comment]
#331 is the issue

**Comment by dbecher-ito** [comment]
Hey - just a quick question: any note on when 3.0.0 will be released? :)

**Comment by hotchemi** [comment]
@dbecher-ito we're trying to release on 8/31 or 9/1 for now! https://github.com/permissions-dispatcher/PermissionsDispatcher/milestone/22

**Comment by aurae** [comment]
This is considered as part of #358
