### ISSUE TITLE
Rename generated method *withCheck to *withPermissionCheck

### ISSUE THREAD

**Issue by UlrichRaab** [permissions-dispatcher/PermissionsDispatcher#355]
Hi i am using this lib for permission management and so far it works great. One thing that could be improved is the naming of the generated methods. If i want to show the camera i am calling the generated method **showCameraWithCheck**. In my opinion it would be clearer if the name of the method is **showCameraWithPermissionCheck**.

**Comment by hotchemi** [comment]
@UlrichRaab Thx!
I think it's more declarative but on the other hand not sure it's worth to change cuz it'd break current API compatibility. Let us consider a bit 🙇

**Comment by aurae** [comment]
Call sites to PD's generated code are already pretty verbose & long, so I'm unsure if we should extend the length even more (I mean, just look at `MainActivityPermissionsDispatcher.showCameraWithPermissionCheck()` 😲). We could still rethink the names for our upcoming major version increment, though! I'd prefer a longer method name like you suggested, if we could cut down on the class name, maybe.

**Comment by shiraji** [comment]
Are we able to call the method without class name in v3.0.0 when we use Java?

**Comment by hotchemi** [comment]
> Are we able to call the method without class name in v3.0.0 when we use Java?

Generally speaking if user do static import we can!

**Comment by hotchemi** [comment]
Tough problem...in Java each methods belong to `XXXPermissionsDispatcher` class so it's predictable that check stands for permission check I guess.
But as for Kotlin we just generate extension method so user may get confused what `check` actually means.

@UlrichRaab are you using Java ver? what do you think about my thought above?

**Comment by aurae** [comment]
Yeah, Kotlin is not a problem here (in regards to the class name), it's the Java side that causes the verbose call site. In general, I do agree that we might change the signature format for 3.x.

**Comment by UlrichRaab** [comment]
@hotchemi I recently switched to Kotlin. The Java naming is pretty clear but in Kotlin you can get confused what **check** means if you are not familiar with PermissionDispatcher.

**Comment by hotchemi** [comment]
@UlrichRaab ah then that makes sense...! didn't know many users are using Kotlin ver than we expected 😅
So I guess it's acceptable to change the name because we haven't released 3.x officially!

**Comment by UlrichRaab** [comment]
@hotchemi Sorry that was my mistake. I should have wrote this in my first post

**Comment by hotchemi** [comment]
@aurae Are you working this issue(just in case)?

**Comment by aurae** [comment]
I haven't touched the generated method signatures yet while working on #350. Is the decision to migrate to `xxxWithPermissionCheck()` final?

**Comment by hotchemi** [comment]
OK! yeah we're going to change as `xxxWithPermissionCheck()` only in Kotlin! I'll take the issue~

**Comment by aurae** [comment]
Only in Kotlin? Instead, we could encourage users to use static imports in Java, and change it for both languages. That would make the experience more consistent, even if users would make use of the interop between both languages, and call the Kotlin code from Java.

**Comment by hotchemi** [comment]
I basically agree with you, my only concern is it breaks API compatibility...but as you pointed out using different method name is absolutely weird...🤔 Do you guys think it's acceptable to change the method name?

**Comment by aurae** [comment]
I feel like a major version increment is the best time to push through with an incompatible change like this, so I'd probably go for it! @shiraji what do you think?

**Comment by shiraji** [comment]
I agree with you guys. I think the user will confuse because of the differences in Java/Kotlin. I think v3.0.0 is the only time that we can make this big changes. I expect to change both Java/Kotlin method call `*WithPermissionCheck`. I'm not sure we should encourage users to use static import in Java. But we can write that in README for sure.
