### ISSUE TITLE
buildToolsVersion "26.0.1" does not generate XXXDispatcher

### ISSUE THREAD

**Issue by Lalalatte** [permissions-dispatcher/PermissionsDispatcher#357]
using sample project
change buildToolsVersion to "26.0.1" then clean for two or three times can reproduce

**Comment by hotchemi** [comment]
@Lalalatte thx for your report. What is the error message?

**Comment by Lalalatte** [comment]
there are some warnings but gradle build success

using buildToolsVersion "25.0.2" , the generated file path is sample/build/generated/source/apt/debug/permissions.dispatcher.sample/MainActivityPermissionsDispatcher
using buildToolsVersion "26.0.1",  there is no apt folder under sample/build/generated/source, so there is no XXXDispatcher

**Comment by Lalalatte** [comment]
It seems that update JAVAPOET_VERSION to 1.9.0 can solve this.

**Comment by hotchemi** [comment]
@Lalalatte I think it's not because of JavaPoet but probably the generated file path is changed...?
Can you cause this problem all the time? and can you guess why JavaPoet 1.9.0 resolved the issue?

**Comment by aurae** [comment]
I can't reproduce this issue with the following build environment:

```
# Android configuration
COMPILE_SDK_VERSION=android-26
BUILD_TOOLS_VERSION=26.0.1
TARGET_SDK_VERSION=26
MIN_SDK_VERSION=14
```

**Comment by hotchemi** [comment]
I guess this is not a problem of library so let me close for the time being.

**Comment by Lalalatte** [comment]
@aurae  You may try Clean Project and then Rebuild Project after sync.

**Comment by allo86** [comment]
I am facing this issue too. Is there something that you would like me to check in my project? I can't upload the code. I am using buildTools 26.0.0 and targetSdk 26.

**Comment by shiraji** [comment]
Can you create a minimum reproducible project and share with us? Otherwise, we are not going to investigate this problem since @aurae already verified that this is not happening https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/357#issuecomment-325629344

**Comment by allo86** [comment]
I was able to create a minimum reproducible project. Please find it attached.
[CleanArchitectureSample.zip](https://github.com/permissions-dispatcher/PermissionsDispatcher/files/1318826/CleanArchitectureSample.zip)

**Comment by hotchemi** [comment]
@allo86 please add `annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:${latest.version}"` like dagger.
