### ISSUE TITLE
Migrate Lint Rules to UAST

### ISSUE THREAD

**Issue by aurae** [permissions-dispatcher/PermissionsDispatcher#359]
#331 is most likely caused by the incomplete support of the PSI-based API currently used by our Lint rules. JetBrains devised a new API called "UAST" (Unified AST), with a primary goal being to support both Java and Kotlin. We should migrate our rules over to this new API, which mainly involves renaming a few classes in the best case scenario (under the hood, PSI is still being used, just the entry points are described differently).

My go-to resource for this migration is [a thread on Google Groups](https://groups.google.com/forum/#!topic/lint-dev/7nLiXa04baM), where Tor Norbye describes the migration process. Let's consider this before the first 3.0.0 alpha release!

**Comment by hotchemi** [comment]
@aurae thank you! let me work on.

**Comment by hotchemi** [comment]
Now I'm working on https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/363 and found one unclear point so posted a question to google group thread.
