### ISSUE TITLE
why I  can not  generous  MainActivityPermissionsDispatcher([Activity Name] + PermissionsDispatcher)

### ISSUE THREAD

**Issue by yanchengdeng** [permissions-dispatcher/PermissionsDispatcher#361]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by yanchengdeng** [comment]
even use the permissionsDispatcher plugin ,but also can generous the class under the folder(build-->intermediates-->classes-->debug-->...)
please give me use this gradle ,we should notice  some tips!thx!

**Comment by yanchengdeng** [comment]
even use the permissionsDispatcher plugin ,but also can generous the class under the folder(build-->intermediates-->classes-->debug-->...)
please give me some tips  about  using this grade

**Comment by hotchemi** [comment]
@yanchengdeng please check your gradle and annotation processing setup again with readme. if you'll not be able to solve the problem go to stackoverflow.

**Comment by yanchengdeng** [comment]
even use the permissionsDispatcher plugin ,but   can not  generous the class under the folder(build-->intermediates-->classes-->debug-->...) to use ！
please give us some tips about using this grade.
