### ISSUE TITLE
NeedsPermission annotated method with parameter doesn't work in Kotlin

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#376]
Log: https://gist.github.com/ryugoo/cf8d4057973eac940c7713e054c02c35

**Comment by shiraji** [comment]
There are multiple issues here.
* kotlin.String converts to java.lang.String
* `GrantableRequest` declares as `val`
* `GrantableRequest` should be nullable and initializes as null
* `XxxPermissionRequest` has property that is the same name with primary constructor's one.

I am working on GrantableRequest and XxxPermissionRequest problems.

**Comment by hotchemi** [comment]
Thx! I've just worked on it and here's a patch file.

[patch.txt](https://github.com/permissions-dispatcher/PermissionsDispatcher/files/1308942/patch.txt)
