### ISSUE TITLE
CallNeedsPermission check incorrectly flags calls to methods of different class

### ISSUE THREAD

**Issue by zergtmn** [permissions-dispatcher/PermissionsDispatcher#377]
Version 3.0.0
When calling a method of another class that has the same name as `@NeedsPermission` method of activity the Lint check incorrectly flags it:
![](https://i.imgur.com/dA0Zb9M.png)

**Comment by hotchemi** [comment]
@zergtmn thx! this is a bug.
we're planning to release 3.0.1 so let us include this fix to the ver.

**Comment by hotchemi** [comment]
https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/379

**Comment by hotchemi** [comment]
@zergtmn please check 3.0.1!

**Comment by zergtmn** [comment]
@hotchemi that was really fast. Thank you!
