### ISSUE TITLE
 Why is the new version incompatible with older versions?

### ISSUE THREAD

**Issue by shunfayang** [permissions-dispatcher/PermissionsDispatcher#387]
I use `` latest.release lib permissions-dispatcher`` for my project.But today,I complie the project and then error. New method name is incompatible with old method name.

Like:
``
old: FragmentOrderSendPermissionsDispatcher.getChatPermissionWithCheck(FragmentOrderSend.this);
new:FragmentOrderSendPermissionsDispatcher.getChatPermissionWith**Permission**Check(FragmentOrderSend.this);
``

Is it possible recover to before?Or must use new method name？

**Comment by hotchemi** [comment]
@shunfayang we changed the method name from 3.x, please refer to our migration guide to do a migration.
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md#migrating-to-permissionsdispatcher-3x

**Comment by shunfayang** [comment]
Thanks for your help.
