### ISSUE TITLE
kt file generation doesn't work with incremental build

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#388]
## Overview

I got a feedback on Twitter that with `kotlin.incremental=true` .kt file generation doesn't work🤔
Not sure that's a bug of our side or kapt side but we need more info/investigation for it!

ref: https://twitter.com/macha1972/status/913170272194256896 (Japanese)

**Comment by hotchemi** [comment]
seems it's a bug of kapt...let me close for the time being.

**Comment by mannodermaus** [comment]
Is there a ref link for a YouTrack issue or something along these lines?

**Comment by hotchemi** [comment]
Sorry I dunno but the reporter said DataBinging has a same issue now 🤔 
https://twitter.com/macha1972/status/913190550123114496

**Comment by mannodermaus** [comment]
Oh, alright. Very odd, especially since incremental compilation has been the default for a while now, and I haven't run into that problem in a long time. Let's observe it, but for now there's nothing to be done on our side!
