### ISSUE TITLE
kt generation files with package name `in` Don't automatically add tilda and hence compilation fails 

### ISSUE THREAD

**Issue by LadwaAditya** [permissions-dispatcher/PermissionsDispatcher#389]
## Overview

- If we have a package name with `in` build fails

### Expected

- Generated files should automatically have Tilda appended 

### Actual

- The package name doesn't have Tilda appended so that builds don't fail

## Environment

-- v 3.0.1 on Kotlin file(MainActivity.kt)

**Comment by mannodermaus** [comment]
Good catch! Thanks for bringing that up. We might forward this to the kotlinpoet team, however, instead of handling the reserved keywords ourselves.

**Comment by LadwaAditya** [comment]
Looks cool :+1:

**Comment by mannodermaus** [comment]
Raised for discussion on https://github.com/square/kotlinpoet/issues/247

**Comment by hotchemi** [comment]
👍 👍 👍

**Comment by mannodermaus** [comment]
Quick update: This has been fixed in kotlinpoet and will be available in their next release (and in consequence, our next version as well)!

**Comment by hotchemi** [comment]
So quick work!!!

**Comment by LadwaAditya** [comment]
Cool.

**Comment by mannodermaus** [comment]
In the meantime, and if you don't mind the extra ceremony, you can make this work right now by using the latest SNAPSHOTs of PermissionsDispatcher and kotlinpoet directly:

```groovy
repositories {
    // TODO Remove after release of PermissionsDispatcher 3.1.0 Stable: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/389
    maven { url "https://oss.jfrog.org/oss-snapshot-local" } // PermissionsDispatcher Snapshot
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" } // kotlinpoet Snapshot
}

dependencies {
    // TODO Move to stable version after kotlinpoet update: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/389
    implementation "com.github.hotchemi:permissionsdispatcher:3.1.0-SNAPSHOT"
    kapt "com.github.hotchemi:permissionsdispatcher-processor3.1.0-SNAPSHOT"
    kapt "com.squareup:kotlinpoet:0.6.0-SNAPSHOT" // Remove this after release of PermissionsDispatcher 3.1.0 Stable
}
```

**Comment by mannodermaus** [comment]
KotlinPoet 0.6.0 has been released with the expected fix to this issue. @hotchemi we can now move forward with a new release ourselves & close this afterwards!
