### ISSUE TITLE
How to use startActivityForResult with OnNeverAskAgain

### ISSUE THREAD

**Issue by guuilp** [permissions-dispatcher/PermissionsDispatcher#391]
___

## Overview
This is what I need to do:
If the user marks the NEVER ASK AGAIN, I'd like to open the App settings to let the user activate it from there, and then catch result of the settings permissions activity. See the bellow details and say if I'm missing something, please.

How I'm trying to do:
```
    @OnNeverAskAgain(Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION)
    fun openSettings(){
        val myAppSettings = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.parse("package:" + packageName))
        myAppSettings.addCategory(Intent.CATEGORY_DEFAULT)
        myAppSettings.flags = Intent.FLAG_ACTIVITY_NEW_TASK
        startActivityForResult(myAppSettings, REQUEST_APP_SETTINGS)
    }
```

```
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        onActivityResult(requestCode, resultCode, data)
        if(requestCode == REQUEST_APP_SETTINGS && resultCode == Activity.RESULT_OK){
            if(hasPermissions(Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION)){
                toast("permissions granted!")
            } else {
                toast("permissions not granted!")
            }
        }
    }
```

### Expected
The onActivityResult method to be called.

### Actual
Method onActivityResult not being called.

## Environment

- Which library version are you using?
**3.0.1**
- On which devices do you observe the issue?
**Nexus 5x - Android 8.0 (AVD)**

**Comment by mannodermaus** [comment]
You probably want to avoid the infinite loop in `onActivityResult` by changing its first line to call `super.onActivityResult` instead. Other than that, based from the code you've shared, this looks OK.

Two follow-ups: Do you delegate the handling of `onRequestPermissionsResult` to the method generated by the library as well? Do you use `withPermissionCheck` to call the permission-protected resource in the first place?

**Comment by guuilp** [comment]
@mannodermaus thanks for the advice. But even removing the onActivityResult call and including the super call, didn't work.

About your second question, yes:

```
    @SuppressLint("NeedOnRequestPermissionsResult")
    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        onRequestPermissionsResult(requestCode, grantResults)
    }
```

```
        findMeButton.setOnClickListener {
            closeActivityWithPermissionCheck()
        }
```

**Comment by guuilp** [comment]
It's weird, because I can debug the method NeedsPermission but not the one with OnNeverAskAgain the execution doesn't stop on breakpoint.

**Comment by guuilp** [comment]
I made a few tests here and looks like an activity issue. This code doens't call the activityResult: 

```
val myAppSettings = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.parse("package:" + packageName))
        myAppSettings.addCategory(Intent.CATEGORY_DEFAULT)
        myAppSettings.flags = Intent.FLAG_ACTIVITY_NEW_TASK
        startActivityForResult(myAppSettings, REQUEST_APP_SETTINGS)
```
