### ISSUE TITLE
xiaomi show permission dialog twice when i request Location permission

### ISSUE THREAD

**Issue by wangchong33333** [permissions-dispatcher/PermissionsDispatcher#395]
## Overview

 xiaomi show permission dialog twice when i request Location permission，first dialog has 10 seconds countdown and auto deny operation，second has not  countdown。Is this a problem？

### Expected

- It should show dialog once。

## Environment

-library：3.0.1
- xiaomi 5   android 7.0

**Comment by hotchemi** [comment]
> first dialog has 10 seconds countdown and auto deny operation

Sorry I don't get it...could you elaborate or paste the gif?
Anyway, please try without PermissionsDispatcher and compare the result.

**Comment by bappleug** [comment]
With new update to support permission on xiaomi device, this issue is introduced.
The reason I found that is because these checking operation will both trigger permission dialogs:
- AppOpsManagerCompat.noteOp()
- ActivityCompat.requestPermissions()
I'm not sure how to avoid this but I think it should be a problem.

**Comment by wangchong33333** [comment]
![12](https://user-images.githubusercontent.com/20990514/31529852-92ad48ca-b00e-11e7-9e72-28bcd7697886.gif)
Like this.And this make another problem,if i request permission in onCreate(),the first dialog will show but the activity layout did not show.I try without PermissionsDispatcher and it has no problem.

**Comment by wangchong33333** [comment]
Now,i use library 2.2.1,it work well.

**Comment by bappleug** [comment]
I think Xiaomi has fixed this issue in later versions. So it is hard to decide when to do the double check. My workaround is to temporarily modify Build.MANUFACTURER other than "Xiaomi" to avoid the check.

**Comment by shiraji** [comment]
So can I close this issue?

**Comment by wyl530274554** [comment]
-library：3.3.1

xiaomi note3 android 8.1

I have the same problem.

**Comment by liqing338** [comment]
”OnNeverAskAgain“  this method is called all the time！ in Nokie X7-android8.1；
i 'm use 3.3.1 version

**Comment by hotchemi** [comment]
Just merged https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/548 so it will be fixed in next version may be(you can test with snapshot)?
