### ISSUE TITLE
PermissionDispatcher works not properly on my RedMi Note4,But it's normal on HuaWei (android 7.0)。

### ISSUE THREAD

**Issue by JeremyHwc** [permissions-dispatcher/PermissionsDispatcher#396]
I downloaded your PermissionsDispatcher project and build it ,but when I installed the smple app in my RedMi Note 4 (android 6.0),I found it not work properly.So I bought a HuaWei ,it worked properly.

RedMi Note4:
         onCameraNeverAskAgain(just this method called )

huawei nova:
         onContactsDenied: 
         showRationaleForContact: 
          showRationaleDialog: 
         onContactsDenied: 
         showRationaleForContact: 
         showRationaleDialog: 
         showContacts: 
         showContacts:

**Comment by shiraji** [comment]
Does the app call `MainActivityPermissionsDispatcher.showCameraWithPermissionCheck(MainActivity.this);`?

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/sample/src/main/java/permissions/dispatcher/sample/MainActivity.java#L26

**Comment by hotchemi** [comment]
Could we get the sample?
