### ISSUE TITLE
nullable params with Kotlin

### ISSUE THREAD

**Issue by vincentnock** [permissions-dispatcher/PermissionsDispatcher#397]
## Overview

When the function annotated with `@NeedsPermission` has a nullable parameter, the generated function in the dispatcher have a non nullable one instead.

### Expected

The `**WithPermissionCheck` generated method should use a nullable parameter too

### Actual

The `**WithPermissionCheck` use a non-nullable parameter

## Environment

- v3.0.1

## Reproducible steps

```kotlin
//Function in Activity
@NeedsPermission(Manifest.permission.ACCESS_COARSE_LOCATION)
internal fun functionWithNullableParameter(string: String?) {
    //...
}

//Generated function in the PermissionsDispatcher
fun HomeActivity.functionWithNullableParameterWithPermissionCheck(string: String) {
    //...
}

```

**Comment by mannodermaus** [comment]
Thanks for reporting! Yeah, we should obey the nullability of parameters given to permission-protected methods.
