### ISSUE TITLE
NeedsPermission and OnPermissionDenied have to have same permissions set or OnPermissionDenied is never called

### ISSUE THREAD

**Issue by chpasha** [permissions-dispatcher/PermissionsDispatcher#404]
## Overview

If NeedsPermission and OnPermissionDenied have different sets of permissions (for instance if I ask for Permission A and B but want to react to denial of any of them differently) - OnPermissionDenied is never called

### Expected

I expect every defined OnPermissionDenied method to be called if the permission it requires is denied OR at least describe this limitation in doc explicitly - for now it is not obvious that you can't have more than one OnPermissionDenied method and both annotations have to reference same permission set and throw some exception that permission sets are not equal or smth. like that

### Actual

OnPermissionDenied is not called if it has only subset of requested permissions

## Environment

- Which library version are you using? 3.0.1
- On which devices do you observe the issue? Any android emulator

## Reproducible steps
if you have more than on OnPermissionDenied method or just one with subset of permissions (doesn't make sense, but demonstrates that the method is never called without any exception or at least warning)

```
@NeedsPermission({
		Manifest.permission.ACCESS_FINE_LOCATION /*OPTIONAL*/,
		Manifest.permission.GET_ACCOUNTS /*Required*/
	})
	@Override
	protected void doWork()
	{
		
	}

	@OnPermissionDenied({
		Manifest.permission.ACCOUNTS
	})
	void onRequiredPermissionsDenied()
	{
		// we can't go any further, show error and finish
               finish();
	}

    @OnPermissionDenied({
		Manifest.permission.ACCESS_FINE_LOCATION
	})
	void onRequiredPermissionsDenied()
	{
		//we can live without it, just proceed
	}
```

**Comment by shiraji** [comment]
This is expected behavior. PermissionsDispatcher requires to have the exactly same parameters for `NeedsPermission` or any annotations.

**Comment by hotchemi** [comment]
@chpasha yes, this is an expected behavior. Please set the same parameters to each annotations~

**Comment by chpasha** [comment]
fair enough, but maybe you could mention this in documentation and/or showing warning during annotation processing (or even throw exception). for now only android studio check shows that OnPermissionDenied method is never used
