### ISSUE TITLE
Lint wants @OnShowRationale values to exactly match @NeedsPermission's values, doesn't handle @OnShowRationale having only a subset of @NeedsPermission's values.

### ISSUE THREAD

**Issue by vlazzle** [permissions-dispatcher/PermissionsDispatcher#405]
Lint wants @OnShowRationale values to exactly match @NeedsPermission's values, it throws an error when @OnShowRationale has only a subset of @NeedsPermission's values.

example:
```
    @NeedsPermission({
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.READ_PHONE_STATE})
    void initializePresenter() {
        ...
    }

    @OnShowRationale({
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION})
    void onShowRationaleLocation(PermissionRequest request) {
        ...
    }

    @OnShowRationale({Manifest.permission.READ_PHONE_STATE})
    void onShowRationalePhoneState(PermissionRequest request) {
        ...
    }

```

**Comment by hotchemi** [comment]
@vlazzle thx for your feedback! Actually this is correct in terms of specification because we treat permissions as an array so that we regard any subset as different permissions set to make library usage simple and intuitive!

**Comment by vlazzle** [comment]
@hotchemi  does this mean that the above usage is incorrect? This would be surprising because:
1. It works.
2. Requesting multiple permissions at once but showing different rationales for a subset of the requested permissions seems like a typical use case.
