### ISSUE TITLE
 PermissionsDispatcher

### ISSUE THREAD

**Issue by caoanqi** [permissions-dispatcher/PermissionsDispatcher#409]
PermissionsDispatcher is not automatically generated

build.gradle:
dependencies {
 compile("com.github.hotchemi:permissionsdispatcher:3.0.1") {
        // if you don't use android.app.Fragment you can exclude support for them
        exclude module: "support-v13"
    }
    annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:3.0.1"
}

**Comment by hotchemi** [comment]
We need more information to go into. @caoanqi please check README again and reopen if needed

**Comment by caoanqi** [comment]
Already solved. thanks
