### ISSUE TITLE
@OnShowRationale annotated method can't be called for the first time

### ISSUE THREAD

**Issue by zcelaloglu** [permissions-dispatcher/PermissionsDispatcher#414]
## FAQs

 ___

## Overview
- I just wanna show a dialog before I ask location permission

### Expected
Dialog should be showned before I ask location permission but it is not working for the first time but after I denied and then ask again everything working properly

### Actual
Dialog should be showned before I ask location permission but it is not working for the first time but after I denied and then ask again everything working properly

## Environment

- Which library version are you using? 3.0.1
- On which devices do you observe the issue? every device I tried
- Note any other information that might be useful

## Reproducible steps
 // here is not called
@OnShowRationale({Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION})
    void showRationale(final PermissionRequest request) {
        permissionDescription(request);
    }

private void permissionDescription(final PermissionRequest request) {
        CustomAlertDialog dialog = new CustomAlertDialog.Builder(this, R.drawable.ic_error_alert)
                .setTitle(getString(R.string.permission_not_granted_dialog_title))
                .setMessage(getString(R.string.location_permission_description_dialog_message))
                .setNeutralButtonText(getString(R.string.general_ok))
                .build();
        dialog.show();
        dialog.setOnNeutralButtonClickListener(() -> {
            dialog.dismiss();
            request.proceed();
        });
    }

**Comment by hotchemi** [comment]
We don't support showing a dialog before asking permission. So please address on your side!
Thank you for your interest!
