### ISSUE TITLE
Apply for multiple permissions, all allow callback or application failed callback

### ISSUE THREAD

**Issue by shuangqingfeng** [permissions-dispatcher/PermissionsDispatcher#417]
I welcome page, apply for multiple sets of permissions and all clicks allowed but the callback or application failed, how to solve?

**Comment by hotchemi** [comment]
@shuangqingfeng sorry I couldn't get the problem...could you elaborate if needed? 🙇 
Let me close the issue for the time being, thank you for your interest!
