### ISSUE TITLE
conflict with the project objectbox-java,  java file like MainActivityPermissionsDispatcher can not be generate

### ISSUE THREAD

**Issue by yuerolling** [permissions-dispatcher/PermissionsDispatcher#418]
hi  ,I have test this on a new test project ,when it run alone ,it run  good。But when i add  project support of https://github.com/objectbox/objectbox-java,  become bad.  The android studio report errors like 

 error: can not find 
                MainActivityPermissionsDispatcher.showCameraWithPermissionCheck(MainActivity.this);

here are  two gradle files:
buildscript {
    ext.kotlin_version = '1.1.51'
    ext.objectboxVersion = '1.3.4'  //object box
    repositories {
        google()
        jcenter()
        maven { url "http://objectbox.net/beta-repo/" }//object box
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "io.objectbox:objectbox-gradle-plugin:$objectboxVersion"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "http://objectbox.net/beta-repo/" }//object box
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

pply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-kapt'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'io.objectbox'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.banma_bjb_141622.myapplication"
        minSdkVersion 24
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'

    implementation("com.github.hotchemi:permissionsdispatcher:3.0.1") {
        exclude module: "support-v13"
    }
    annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:3.0.1"

}

**Comment by yuerolling** [comment]
sorry  ,I think  it cause by  https://github.com/objectbox/objectbox-java,  may it not support newest version of  android studio  with   kotlin. If I remove support of kotlin ,it work well.

**Comment by lnpusong123** [comment]
I came with the same problem, bu i use java.

**Comment by yuerolling** [comment]
@lnpusong123   now  ,it is  ok ,but I remove the library of permission dispatcher, I think the problem may caused  by aapt

**Comment by lnpusong123** [comment]
I solved the problem. It's my mistake,i ignore the NOTE: Annotated methods must not be private.
I use objectbox 1.4.0.
