### ISSUE TITLE
build release app,Grade make a error.

### ISSUE THREAD

**Issue by xieyingwu** [permissions-dispatcher/PermissionsDispatcher#423]
Information:Gradle tasks [:app:assembleRelease]
Error:java.lang.ClassNotFoundException: com.android.tools.lint.detector.api.Detector$UastScanner

**Comment by xieyingwu** [comment]
the reason of this error is the hint.jar is not the newest.

**Comment by xieyingwu** [comment]
grade version is 3.3;
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

**Comment by hotchemi** [comment]
Please update android gradle plugin to align Android Studio 3. I'd say you're using old one. Thank you!
