### ISSUE TITLE
annotation @RuntimePermissions @NeedsPermission add on baseactivity 

### ISSUE THREAD

**Issue by techinsight** [permissions-dispatcher/PermissionsDispatcher#426]
## FAQs

 
___

## Overview

Now annotations @RuntimePermissions @NeedsPermission cannot be added in a  baseactivity , and handle the result for denied or never hint annotations in subclasses??!

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by hotchemi** [comment]
To keep a simpleness of the library we wanna keep current API and limitation, thx for your feedback!
