### ISSUE TITLE
Kotlin generation doesn't keep types of Array or ArrayList

### ISSUE THREAD

**Issue by vincentnock** [permissions-dispatcher/PermissionsDispatcher#427]
## Overview

```kotlin
@NeedsPermission(Manifest.permission.CAMERA)
- fun aFunction(option: Array<out String>) {
…
}
```

### Expected

```kotlin
fun Activity.aFunctionWithPermissionCheck(option: Array<out String>) {
…
}
```
I expect both Kotlin String type and out modifier to be kept.

### Actual

```kotlin
fun Activity.aFunctionWithPermissionCheck(option: Array<java.lang.String>) {
…
}
```

Note that Any is translated to java.lang.Object too (probably same problem)

Same behavior with `ArrayList<String>`

## Environment

- Which library version are you using? : 3.1.0

**Comment by hotchemi** [comment]
@vincentnock thx! we gotta fix the problem...our implementation relies on https://github.com/square/kotlinpoet and it might cause the thing 🤔

**Comment by vincentnock** [comment]
Maybe related to this issue ?
https://github.com/square/kotlinpoet/issues/86

**Comment by hotchemi** [comment]
Working on https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/509 but CI failed.. 🤔

**Comment by hotchemi** [comment]
You can test with 4.0.0 snapshot! thank you for your heads up.
