### ISSUE TITLE
Annotation processors must be explicitly declared now

### ISSUE THREAD

**Issue by Kevin1466** [permissions-dispatcher/PermissionsDispatcher#428]
Error:Execution failed for task ':LGMain:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - permissionsdispatcher-processor-3.1.0.jar (com.github.hotchemi.permissionsdispatcher:permissionsdispatcher-processor:3.1.0)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

**Comment by mannodermaus** [comment]
Have you checked your dependency declaration based on what the error is telling you? The `permissionsdispatcher-processor` library has to be added to the `annotationProcessor` configuration, not `compile`, `api` or `implementation`. Please review how the library is included in your project!
