### ISSUE TITLE
Fragment's onActivityResult() is not called when requesting SYSTEM_ALERT_WINDOW permission

### ISSUE THREAD

**Issue by dennis-pelluzi-artit** [permissions-dispatcher/PermissionsDispatcher#429]
## Overview

- I'm using `@RuntimePermissions` with  an `android.support.v4.app.Fragment` and I need request `SYSTEM_ALERT_WINDOW` permission using `@NeedsPermission(Manifest.permission.SYSTEM_ALERT_WINDOW)`.
According to documentation I must override `onActivityResult()` calling the generated `onActivityResult()` of PermissionDispatcher. However, Fragment's onActivityResult() is not called when I back from app settings.
The issues occurs because the generated fragment extension use `activity.startActivityForResult()`. When using activity method, the fragment's onActivityResult() is not called. The library should use `fragment.startActivityForResult()` instead.

### Expected

- The method `onActivityResult()`of Fragment should be called.

### Actual

- The method `onActivityResult()`of Fragment is not called.

## Environment

Library version is 3.1.0
Kotlin plugin 1.1.60

**Comment by hotchemi** [comment]
@dennis-pelluzi-artit Thx! would you mind sending a PR?

**Comment by dennis-pelluzi-artit** [comment]
@hotchemi Yes, I can send a PR. Thanks for replying.
