### ISSUE TITLE
MainActivityPermissionsDispatcher not found

### ISSUE THREAD

**Issue by yuerolling** [permissions-dispatcher/PermissionsDispatcher#430]
Hi,when I use the sample provided by this project  ,it is all right ,but when I add   apply plugin: 'kotlin-kapt'
to the file of build.gradle ,the problem occur , 
I can not use it like this？

**Comment by hotchemi** [comment]
Please make sure your build setting is correct, and also try to post a question to stackoverflow, thx.

**Comment by yuerolling** [comment]
I just added a word to your project's build gradle file. . .
