### ISSUE TITLE
XIAO MI NOTE

### ISSUE THREAD

**Issue by shuangqingfeng** [permissions-dispatcher/PermissionsDispatcher#432]
XIAO MI NOTE denied permission to apply again after the application does not appear permission to apply dialog box, manually set permissions in the application management page allows, but still does not apply for permission to check the permissions

**Comment by hotchemi** [comment]
any idea to deal with/improve?

**Comment by a1018875550** [comment]
no way, they don't recognition change the permissions ,but they do.
