### ISSUE TITLE
OnShowRationale method handling using DialogFragment

### ISSUE THREAD

**Issue by shiraji** [permissions-dispatcher/PermissionsDispatcher#434]
The problem is if the developers want to provide decorated dialog for OnShowRationale, they must use DialogFragment. Like this https://twitter.com/sys1yagi/status/962983697354964992

At this moment, we cannot do this because `PermissionRequest` is not `Serializable` or `Parcelable`. 

Here is the whole thread:
https://twitter.com/sys1yagi/status/962954216292589569

I'm not quite sure how we can tackle this problem at this moment...

**Comment by hotchemi** [comment]
@shiraji Thx for your heads up!

**Comment by kenshin171** [comment]
Any updates on this issue? i am also facing this problem and am not sure how to handle it currently.

**Comment by hotchemi** [comment]
May be we can use coroutine concept? 🤔

**Comment by hotchemi** [comment]
One possible way is to make PermissionRequest class public and write a code like below:

```java
public class SampleFragment extends DialogFragment {
    private PermissionRequest request;

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        request = new PermissionRequest(activity) // or caller fragment
    }

    // call request.proceed() or cancel() as appropriate
} 
```

**Comment by hotchemi** [comment]
After a long consideration my idea is below 🤔 

1. Generate `requestPermissions` method when `OnShowRationale` annotated method exists.

```java
static void requestPermissions(@NonNull MainActivity target) {
  ActivityCompat.requestPermissions(target, PERMISSION_SHOWCONTACTS, REQUEST_SHOWCONTACTS);
}
```

2. Fix `OnShowRationale` annotated method to use `XXXPermissionsDispatcher.requestPermissions` and `OnPermissionDenied` annotated method. Then we can remove `PermissionRequest` interface from code.

```java
@OnShowRationale(Manifest.permission.CAMERA)
void showRationaleForCamera() {
  new AlertDialog.Builder(this)
    .setMessage(R.string.permission_camera_rationale)
    .setPositiveButton(R.string.button_allow, (dialog, button) -> XXXPermissionsDispatcher.requestPermissions(this))
    .setNegativeButton(R.string.button_deny, (dialog, button) -> onCameraDenied())
    .show();
}
```

Then we can cope with DialogFragment:

```java
public class XXXFragment extends DialogFragment {
    private XXXActivity activity;

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        if (activity instanceof XXXActivity) {
            activity = (XXXActivity) activity;
        }
    }

    // call XXXPermissionsDispatcher.requestPermissions(activity) or activity.onCameraDenied
} 
```

Pros:

- would be easy for user to deal with DialogFragment
- Code generation logic would become a bit shorter

Cons:

- would break backward compatibility
- API would become a bit counter-intuitive?

@permissions-dispatcher/maintainers what do you think? 👀

**Comment by kenshin171** [comment]
can we have a sample on dialogfragment usage of  `XXXPermissionsDispatcher.proceedPermissionRequest and XXXPermissionsDispatcher.cancelPermissionRequest annotated methods.` ?
