### ISSUE TITLE
@OnNeverAskAgain method was called when user denied SYSTEM_ALERT_PERMISSION

### ISSUE THREAD

**Issue by phicdy** [permissions-dispatcher/PermissionsDispatcher#436]
## Overview

`SYSTEM_ALERT_PERMISSION` is special permission, user only permits it or not. So `@OnNeverAskAgain` is only for Runtime Permission, but it was called when user denied `SYSTEM_ALERT_PERMISSION`.

### Expected

`@OnPermissionDenied` method will be called

### Actual

`@OnNeverAskAgain` method was called

## Environment

* PermissionDispatcher 3.1.0
* Java/kotlin 1.2.21
* Android 7.1.1/8.0.0 emulator

## Reproducible steps

0. Disable `SYSTEM_ALERT_PERMISSION`  from test app
1. Open test app and go to the setting
2. Not enable the permission
3. Go back to the app by back button

## Test code

```kotlin
@RuntimePermissions
class MainActivity : AppCompatPreferenceActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        systemAlertWindowWithPermissionCheck()
    }

    @NeedsPermission(Manifest.permission.SYSTEM_ALERT_WINDOW)
    fun systemAlertWindow() {
        Log.d("test", "NeedsPermission")
    }

    @OnShowRationale(Manifest.permission.SYSTEM_ALERT_WINDOW)
    fun systemAlertWindowOnShowRationale(request: PermissionRequest) {
        Log.d("test", "OnShowRationale")
    }

    @OnPermissionDenied(Manifest.permission.SYSTEM_ALERT_WINDOW)
    fun systemAlertWindowOnPermissionDenied() {
        Log.d("test", "OnPermissionDenied")
    }

    @OnNeverAskAgain(Manifest.permission.SYSTEM_ALERT_WINDOW)
    fun systemAlertWindowOnNeverAskAgain() {
        Log.d("test", "OnNeverAskAgain")
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        onActivityResult(requestCode)
    }
}
```

**Comment by shiraji** [comment]
Does this issue relate to #435?

**Comment by phicdy** [comment]
No, it's different issue from kotlin setting. It also occurs in Java.

**Comment by hotchemi** [comment]
Sorry for the late and thx for the issue. Would you mind sending PR? 😇

**Comment by phicdy** [comment]
Sorry for late response. I found workaround for this issue.
If we DON'T define `@OnNeverAskAgain(Manifest.permission.SYSTEM_ALERT_WINDOW)`, processor doesn't generate the code to call the never ask method and call permission denied method when user denied the permission.

This is the code diff of generated `MainActivityPermissionsDispatcher`

### When define @OnNeverAskAgain(Manifest.permission.SYSTEM_ALERT_WINDOW)

```
static void onActivityResult(MainActivity target, int requestCode) {
    switch (requestCode) {
      case REQUEST_SYSTEMALERTWINDOW:
      if (PermissionUtils.hasSelfPermissions(target, PERMISSION_SYSTEMALERTWINDOW) || Settings.canDrawOverlays(target)) {
        target.systemAlertWindow();
      } else {
        if (!PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_SYSTEMALERTWINDOW)) {
          target.systemAlertWindowOnNeverAskAgain();
        } else {
          target.systemAlertWindowOnPermissionDenied();
        }
      }
      break;
      default:
      break;
    }
  }
```

### When not define @OnNeverAskAgain(Manifest.permission.SYSTEM_ALERT_WINDOW)

```
static void onActivityResult(MainActivity target, int requestCode) {
    switch (requestCode) {
      case REQUEST_SYSTEMALERTWINDOW:
      if (PermissionUtils.hasSelfPermissions(target, PERMISSION_SYSTEMALERTWINDOW) || Settings.canDrawOverlays(target)) {
        target.systemAlertWindow();
      } else {
        target.systemAlertWindowOnPermissionDenied(); // Expected result !!!!!
      }
      break;
      default:
      break;
    }
  }
```

**Comment by hotchemi** [comment]
Sorry for being late but we've fixed to check in compile time. https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/549
