### ISSUE TITLE
Library generates uncompiled code if @NeedsPermission method has a parameter with keywords in canonical classname

### ISSUE THREAD

**Issue by AlexKorovyansky** [permissions-dispatcher/PermissionsDispatcher#437]
## Overview
In our project, we have `is.effective` as packageName. There are a model class `Image` located in `is.effective.models` package and some fragment with method `foo`, where `Image` is a parameter:
```kotlin
class ChatFragment: Fragment() {
...
   @NeedsPermission(WRITE_EXTERNAL_STORAGE)
   fun longClicked(image: Image) {
      // method code is omitted
   }
...
}
```

### Expected

- Library generates `longClickedWithPermissionCheck` extension method in ChatFragmentDispatcher.kt and generated code is compilable.

### Actual

- Library generates `longClickedWithPermissionCheck` extension method in ChatFragmentDispatcher.kt, but generated code is not compilable, due to inproperly generated import statement (non-escaped `is` keyword):
![screenshot](https://cl.ly/3f2o0d11250C/Image%202018-02-23%20at%204.27.58%20PM.png)

## Environment

- Which library version are you using?
3.1.0

- On which devices do you observe the issue?
that's a compilation error

- Note any other information that might be useful
As I understand, PermissionDispatcher relies on https://github.com/square/kotlinpoet, so we need to address the issue their. I went ahead, forked kotlinpoet, made a local fix and will submit PR to kotlinpoet shortly.

**Comment by mannodermaus** [comment]
Huh, I'm certain that I did that before (edit: [yes I did](https://github.com/square/kotlinpoet/pull/248). @shiraji, @hotchemi, let's review the version of kotlinpoet we're pulling in with the latest version of PermissionsDispatcher. @AlexKorovyansky, can you try adding an explicit dependency on the latest kotlinpoet to the `annotationProcessor` configuration?

**Comment by shiraji** [comment]
We need to wait https://github.com/square/kotlinpoet/pull/327 release. Right? @AlexKorovyansky

**Comment by mannodermaus** [comment]
I see, this actually is somehow different to our previous work - weird. Admittedly, I only skimmed over the related kotlinpoet issue briefly. Okay, let's wait on a new release then!

**Comment by AlexKorovyansky** [comment]
Original PR (https://github.com/square/kotlinpoet/pull/248) fixes only issue in package declaration, while this issue relates to imports. The fix for kotlinpoet has been already merged to master and should be available in 0.8.0-SNAPSHOT. Is there any option to use kotlinpoet 0.8.0-SNAPSHOT with the latest version of PermissionDispatcher?

**Comment by shiraji** [comment]
See https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/389#issuecomment-333682572

**Comment by hotchemi** [comment]
Thx guys! I'd say we need https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/438 ? 👀

**Comment by hotchemi** [comment]
Oh I found with 0.8.0-SNAPSHOT generated kt class causes a compile error as below 🤔 

```kt
(PermissionUtils.hasSelfPermissions(`this`, *PERMISSION_SHOWCAMERA))
```

**Comment by hotchemi** [comment]
Updated KotlinPoet to 1.0.0-RC.
