### ISSUE TITLE
XxxPermissionsDispatcher class is not generated

### ISSUE THREAD

**Issue by wolfVbx** [permissions-dispatcher/PermissionsDispatcher#439]
question is:when I use `permissions-dispatcher` in a demo ，it works . the XxxPermissionsDispatcher class is  generated normally. but when I use  `permissions-dispatcher`  in app  module ，the XxxPermissionsDispatcher class is not generated.both of  build.gradle are correct and  the same.

permissions-dispatcher version is `3.1.0`

`
@RuntimePermissions
public class ShotListActivity extends ShotBaseActivity implements View.OnClickListener
`

`
@NeedsPermission(Manifest.permission.CAMERA)
    void showCamera() {
        Intent intent = new Intent(ShotListActivity.this, CameraActivity.class);
        int itemNum = ShotInfoDao.getInstance().getNewItemNum();
        intent.putExtra("num", itemNum);
        intent.putExtra("type", ShotInfo.TYPE_IMG);
        startActivity(intent);
    }
`

this is java class ,I do not know where it collapses.

**Comment by hotchemi** [comment]
👍

**Comment by qujc** [comment]
it happens to me , did you find the causation？

**Comment by wolfVbx** [comment]
I guess that it was `ButterKnife` that cause this bug,coz `ButterKnife` use Apt  to generate code, `PermissionsDispatcher`  also use Apt ,this may hava  effect on `PermissionsDispatcher`,this two may be in collision. But I donnot explore it .I gave up `PermissionsDispatcher` and write a archtecture by myself,though it was not better than `PermissionsDispatcher` .
