### ISSUE TITLE
Generated onRequestPermissionsResult method not called

### ISSUE THREAD

**Issue by EladJarby** [permissions-dispatcher/PermissionsDispatcher#440]
override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        // NOTE: delegate the permission handling to generated function
        onRequestPermissionsResult(requestCode, grantResults)
    }

    @NeedsPermission(Manifest.permission.CAMERA)
    override fun showCamera() {
        cameraIntent()
    }

    @NeedsPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
    override fun showGallery() {
        galleryIntent()
    }

    @OnPermissionDenied(Manifest.permission.CAMERA)
    override fun showDeniedForCamera() {
        permissionDialog("Camera permission is necessary",{ showCameraWithPermissionCheck() })
    }

    @OnPermissionDenied(Manifest.permission.READ_EXTERNAL_STORAGE)
    override fun showDeniedForGallery() {
        permissionDialog("Gallery permission is necessary",{ showGalleryWithPermissionCheck() })
    }
 
___

## Overview

"Generated onRequestPermissionsResult method not called." error.

### Expected

There is a lint error , but the file was generated and i dont know why the error appear..

### Actual

Lint error with : 
"Generated onRequestPermissionsResult method not called." error.
![image](https://user-images.githubusercontent.com/26364971/36949829-32750814-1ff6-11e8-9972-10a374d48e35.png)

## Environment

- Which library version are you using? **3.1.0**
- On which devices do you observe the issue? **The error on android studio**
- Note any other information that might be useful

**Comment by shiraji** [comment]
Does it happens only if you define multiple permission requests?

**Comment by EladJarby** [comment]
No, it happens for one permission either..

**Comment by shiraji** [comment]
Got it. I don't think current lint support new kotlin feature.

**Comment by hotchemi** [comment]
Sorry for the late, we'll address in next ver.
