### ISSUE TITLE
received status code 401 from server: unauthorized.

### ISSUE THREAD

**Issue by xmuSistone** [permissions-dispatcher/PermissionsDispatcher#441]
needs some help:
![image](https://user-images.githubusercontent.com/12167762/37023141-f4b67da8-215f-11e8-81eb-ec8084a19a06.png)

in project gradle:
classpath 'com.android.tools.build:gradle:3.0.0'<br><br>

in gradle/wrapper/gradlw-wrapper.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip<br>

**Comment by mannodermaus** [comment]
PermissionsDispatcher is not distributed via Jitpack. Please review your module's `repositories` block and make sure to place `jcenter()` above the `maven` declaration for Jitpack.

**Comment by xmuSistone** [comment]
@mannodermaus Should I declare maven in the "**module**" gradle???  I make the repositories block  in my project gradle (not module gradle) like this, but it does not work. 
```xml
repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        google()
    }
```

My problem is: downloading permissions-dispatcher dependency jar is successful, and the compile process is succeeded too. But when running the code（or make the project）, it throws this exception(401 unauthorized). Really need your help. Thanks.

**Comment by xmuSistone** [comment]
I have integrated permissions-dispatcher in my project for a long time, and i have not met any problem before. It just throws exception yesterday. I searched throw google, but still cannot fix this. please lead me a way.
