### ISSUE TITLE
What do you plan to do about framework fragments?

### ISSUE THREAD

**Issue by SUPERCILEX** [permissions-dispatcher/PermissionsDispatcher#445]
Hi there,
I'm a developer on https://github.com/googlesamples/easypermissions and we're trying to figure how best to handle the Android team's announcement that [framework fragments are now deprecated](https://twitter.com/ianhlake/status/971455064274485248) in favor of the support library ones. We're considering deprecating support for framework fragments and then killing all support once Android P launches in Q3.

What are your plans? And to the community here: is that a reasonable move or should framework fragment support be kept around for a few more releases?

**Comment by mannodermaus** [comment]
We have yet to discuss that among the contributors. Personally, I feel the same way about deprecating it now, then removing support altogether in a future release. It would probably a minor version increment to allow for a few critical, cherry-picked bug fixes to go into the "older" version.

@hotchemi, @shiraji, let's keep this in mind.

**Comment by hotchemi** [comment]
@SUPERCILEX @mannodermaus thank you for your proposal! I'm for deprecating it in next update and kill all support after P launching 👍 It'd be really beneficial for maintainers presumably 😀

**Comment by hotchemi** [comment]
Addressed on https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/454 and it'll be shipped in next release! Thank you for your feedback~!
