### ISSUE TITLE
Separate requests

### ISSUE THREAD

**Issue by 3383389** [permissions-dispatcher/PermissionsDispatcher#446]
I have two different methods with 
`@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})`
for pick avatar and background.
And I want in `@OnShowRationale` method show different dialogs for avatar and background explanation.
How can I do this?

**Comment by hotchemi** [comment]
@3383389 then we recommend separating method per each permission. We just wrapped [requestPermissions](https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#requestPermissions(android.app.Activity,%20java.lang.String[],%20int)) of support library.

**Comment by 3383389** [comment]
for example I have 

`@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})
    public void getAvatar() {
        ...
    }
@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})
    public void getCover() {
        ...
    }
@ OnShowRationale({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})
    void showAvatarDialog() {
        ...
    }`
and I can't separate OnShowRationale methods because permissions are the same.
Maybe we can use something like RequestCode in default permissions?

**Comment by hotchemi** [comment]
I meant separating method per each permission but I guess you can use v4's PermissionChecker or our [light-weight wrapper](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/library/src/main/android/permissions/dispatcher/PermissionUtils.java#L16)!

**Comment by 3383389** [comment]
Thank you, I'll try
