### ISSUE TITLE
Know if permission has already been granted

### ISSUE THREAD

**Issue by UNCVR** [permissions-dispatcher/PermissionsDispatcher#447]
There is no built-in way to know if a permission has already been granted.

It could be great to have a simple method in the generated PermissionsDispatcher to know that information.

**Comment by hotchemi** [comment]
@UNCVR You can use `PermissionChecker. hasSelfPermission` but it's just a light wrapper of `support.v4.content.PermissionChecker`!

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/ab94c389673aae3fc3a304b41a40e8373866f852/library/src/main/android/permissions/dispatcher/PermissionUtils.java#L95
