### ISSUE TITLE
It has error when use AndroidStudio3.0

### ISSUE THREAD

**Issue by paomian2** [permissions-dispatcher/PermissionsDispatcher#448]
Error:Execution failed for task ':streamlet-core:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - permissionsdispatcher-processor-2.4.0.jar (com.github.hotchemi.permissionsdispatcher:permissionsdispatcher-processor:2.4.0)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

I add "  javaCompileOptions {
            annotationProcessorOptions {
               // arguments = [ moduleName : project.getName() ]
                includeCompileClasspath true
            }
        }"
  in gradle of app, but  It wasn't work.

**Comment by mannodermaus** [comment]
Please review your `dependencies` block. There are two separate artifacts for PermissionsDispatcher, and they have to be added to the correct configurations: `permissionsdispatcher` goes into `implementation`/`compile`, and `permissionsdispatcher-processor` goes into `annotationProcessor`. If you need further assistance, please share your module's `build.gradle` file so we can review it together.

**Comment by yanshihao3** [comment]
如何解决这个问题的，我也遇到这个问题

**Comment by yanshihao3** [comment]
@mannodermaus 
 //动态权限
    api 'com.github.hotchemi:permissionsdispatcher:3.2.0'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:3.2.0'

**Comment by yanshihao3** [comment]
@paomian2

**Comment by hotchemi** [comment]
sorry we don't understand Chinese 🙇

**Comment by yanshihao3** [comment]
How does this problem be solved？ I also met this problem

**Comment by yanshihao3** [comment]
Thank you
