### ISSUE TITLE
meizu pro7 is can't get Camera Permission

### ISSUE THREAD

**Issue by strugglelin** [permissions-dispatcher/PermissionsDispatcher#457]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by hotchemi** [comment]
Could you give us more info?

**Comment by strugglelin** [comment]
The library has no problem。when I Scan the qr code  ,need to add cameraIsCanUse () method judgment，that is Ok。
