### ISSUE TITLE
Android 7.0 MEIZU have no effect

### ISSUE THREAD

**Issue by cuixiaodong** [permissions-dispatcher/PermissionsDispatcher#462]
I tried to run on meizu's mobile phone, and under the Android7.0 system, I couldn't judge whether the permission was rejected.

**Comment by hotchemi** [comment]
Same as https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/457?

**Comment by cuixiaodong** [comment]
Roughly, the current state of denial, and then the authorization status, is returned with the authorization.

**Comment by hotchemi** [comment]
Sorry I guess before M there's no runtime permissions?

**Comment by hotchemi** [comment]
Let me  close the issue since there's no enough info to go into.
