### ISSUE TITLE
Code Generation Fails with Type mismatch compile error

### ISSUE THREAD

**Issue by thsaravana** [permissions-dispatcher/PermissionsDispatcher#468]
#### Method in my Code
    @NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    fun process(urls: Array<String>, title: String, name: String) {
    }

#### Method generated
    fun MyFragment.processWithPermissionCheck(
        url: Array<java.lang.String>,
        title: String,
        fileName: String
    ) {
    }

`Type mismatch: inferred type is Array<java.lang.String> but Array<kotlin.String> was expected`

### Expected

Code should compile without errors, and the generated `.kt` file should refer `kotlin.String` and not `java.lang.String`

### Actual

Compilation fails with the error `Type mismatch: inferred type is Array<java.lang.String> but Array<kotlin.String> was expected`

## Environment

- Which library version are you using? 3.2.0

**Comment by hotchemi** [comment]
Thank you for your report. let us check.

**Comment by shiraji** [comment]
Same as #427 ?

**Comment by hotchemi** [comment]
sorry for the late, dup of #427 so let me merge.
