### ISSUE TITLE
this lib is not work well in meizu mobile

### ISSUE THREAD

**Issue by newbieandroid** [permissions-dispatcher/PermissionsDispatcher#469]
this lib is not work well on meizu mobile

**Comment by mannodermaus** [comment]
Please elaborate in accordance to our [issue template](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/.github/ISSUE_TEMPLATE.md). What is the problem, expected & actual behavior, etc.?

**Comment by hotchemi** [comment]
Let me close the issue since there's no info yet. Please reopen the issue if needed
