### ISSUE TITLE
Files aren't generated in a Kotlin project

### ISSUE THREAD

**Issue by shrayasr** [permissions-dispatcher/PermissionsDispatcher#470]
## FAQs

All checked here ✅. 
___

## Overview

The `*PermissionsDispatcher` class doesn't get generated and I get a `Unresolved Reference` error when calling `*WithPermissionCheck()`

### Expected

The `*WithPermissionCheck()` function be available 

### Actual

The `*WithPermissionCheck()` function isn't available because the file isn't getting generated

## Environment

- Which library version are you using?
    - `3.2.0`
- On which devices do you observe the issue?
    - Unable to deploy anywhere since its resulting in a compiler error

### Additional Details

- I basically took the code that was in [sample kotlin](https://github.com/permissions-dispatcher/PermissionsDispatcher/tree/master/sample-kotlin) project and recreated it within another one
- Getting the following errors during sync:

      Folder C:\Users\shrayasr\work\code\LearningKTRuntimePermissions3\app\build\generated\source\kaptKotlin\debug
      Folder C:\Users\shrayasr\work\code\LearningKTRuntimePermissions3\app\build\generated\source\kaptKotlin\release
      3rd-party Gradle plug-ins may be the cause
- Using android studio `3.1.2` on Windows 10

## Reproducible steps

- Clone https://github.com/shrayasr/PermissionsDispatcherError
- Build

**Comment by hotchemi** [comment]
Specify `RuntimePermissions` annotation to target Activity.

**Comment by shrayasr** [comment]
Works :+1: 

I didn't read the FAQ clear enough. I thought Runtime Permissions was the class of all annotations. Should've been more keen. Apologies. 

Thank you for helping me out here. Appreciate it. Thanks again for writing this. Its of great assistance 🎉
