### ISSUE TITLE
Support androidx fragment

### ISSUE THREAD

**Issue by shiraji** [permissions-dispatcher/PermissionsDispatcher#472]
Google released [Jetpack](https://developer.android.com/jetpack/) that include Fragment class that the package name is `androidx.fragment.app.Fragment`. There might be other support library classes that need to change, too.

**Comment by hotchemi** [comment]
Thank you! Is it ok to proceed this this task from now right?

**Comment by mannodermaus** [comment]
I think I'd prefer if we waited until `androidx.fragment:fragment` graduates to a stable release before we change to it.

**Comment by shiraji** [comment]
I asked a lot of googlers and finally reached to Yigit. He suggested to me that bump major version and drop support library support. If you really want, then split artifacts and let developers choose.

I like the idea dropping supporting old one, however since many developers use this library, I think we can support androidx like we did it for native fragment. I'm still not sure that default one should be Jetpack or not.

**Comment by mannodermaus** [comment]
Ah, you're referring to generating code for `android.app.support.v4` or `androidx` based on what's available on the classpath? I like the idea, although I think that bumping the major version is a little cleaner. We could define a deadline dates for the current versions, after which we stop pushing fixes out to it, effectively its EOL. New stuff would go to the line backed by `androidx`.

**Comment by forkch** [comment]
Any updates on this? I've forked your library in order to make my project compile again.
https://github.com/forkch/PermissionsDispatcher/commits/androidX

**Comment by hotchemi** [comment]
oh looks nice, is it possible to send PR if possible?

**Comment by forkch** [comment]
Sure, it's failing though right now
https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/488

**Comment by shiraji** [comment]
Now the PR moved to #494

**Comment by hotchemi** [comment]
done!
