### ISSUE TITLE
Support incremental compilation

### ISSUE THREAD

**Issue by mannodermaus** [permissions-dispatcher/PermissionsDispatcher#473]
Gradle 4.7 introduced incremental annotation processing, or InCAP for short. Let's review if our use case can be applied here, so we can speed up project builds using this new incremental mechanism.

More info: https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by hotchemi** [comment]
Yeeeah!

**Comment by hotchemi** [comment]
umm sorry we haven't addressed 🙇

**Comment by autonomousapps** [comment]
Any update on this?

**Comment by hotchemi** [comment]
PR: https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/556
seems this doesn't work well with Kotlin? 🤔

**Comment by hotchemi** [comment]
Kotlin issue on Dagger: https://github.com/google/dagger/issues/1283

**Comment by tasomaniac** [comment]
One trick is to create a thin Gradle module at top level and keep it kotlin-free. Although that will only contain the top-level `DaggerComponent`, the generated code in the `build` is not so small. Keeping it java only at that level with only couple of java files already saves a lot of time.

**Comment by autonomousapps** [comment]
@tasomaniac can you elaborate on how much time is saved with that approach?

**Comment by tasomaniac** [comment]
I'm currently experimenting this with 2 projects. They are both small and highly modularized. Incremental build on 1 line change went from 12-15 secs to 7-8 secs. Since numbers are so small, I wouldn't trust. 

In our big project, it is not easy to do this since the top module is heavy on Kotlin.

In short, you get rid of 3 tasks: kaptGenerateStubs, kapt, kotlinCompile and javac becomes incremental.

**Comment by autonomousapps** [comment]
Theoretically, this makes a lot of sense to me. I just want some good metrics. Might be a useful suggestion I can give people when they ask about improving Android build times. (I work for Gradle and one of my primary missions is helping Android teams improve build perf.) Thanks for the idea!

**Comment by hotchemi** [comment]
Thank you folks, let us know if there's something that is applicable to PermissionsDispatcher!

**Comment by tasomaniac** [comment]
Glad I could help @autonomousapps
