### ISSUE TITLE
Check the permissions on meizu Note6(Flyme 6.1.4.2Q | Android 7.1.2) device always return true.

### ISSUE THREAD

**Issue by iflytek-duan** [permissions-dispatcher/PermissionsDispatcher#476]
___

## Overview

- Cannot judge the status of permissions correctly. Check the permissions on meizu Note6(Flyme 6.1.4.2Q | Android 7.1.2) device always return true.

## Environment

- PermissionsDispatcher library version is 3.2.0.
- On Meizu Note6(Flyme 6.1.4.2Q | Android 7.1.2) device.

**Comment by shiraji** [comment]
Related to https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/303 ?

You need to give us the documentation for how we can support Flyme OS in English. Otherwise, we are not able to start discussing if we can support Flyme OS or not.

**Comment by hotchemi** [comment]
@iflytek-duan can you give us how we should fix the logic?

**Comment by iflytek-duan** [comment]
@shiraji @hotchemi 
Thx.
I found the cause of the problem in the Flyme community, and Flyme always returns true to the native permission by default. They have used their own schemes for authority management, and they have not yet merged the two so that the problem can arise.

My English is bad, I hope you can understand my meaning.

**Comment by hotchemi** [comment]
Thank you but unfortunately we can't understand Chinese..😢
Do you have any suggestion? 🙇 @iflytek-duan

**Comment by iflytek-duan** [comment]
Not yet. If I have a better solution, I will reissue issues.@hotchemi
