### ISSUE TITLE
MainActivityPermissionsDispatcher isn't generated for kotlin files after upgrade to 3.2.0

### ISSUE THREAD

**Issue by luna-vulpo** [permissions-dispatcher/PermissionsDispatcher#481]
## Overview

- After upgrade from 2.4.0 to 3.2.0 files: XxxxActivityPermissionsDispatcher are not generated for kotlin files. 
I have in project java and kotlin files. For java files every thing is ok. But after upgrade to 3.2.0 the files aren't generated for kotlin files. 

Working configuration:
```

    implementation("com.github.hotchemi:permissionsdispatcher:2.4.0") {
        exclude module: "support-v13"
    }
    kapt "com.github.hotchemi:permissionsdispatcher-processor:2.4.0"
```

Not working configuration:

```

    implementation("com.github.hotchemi:permissionsdispatcher:3.2.0") {
        exclude module: "support-v13"
    }
    kapt "com.github.hotchemi:permissionsdispatcher-processor:3.2.0"
```

Is it a known issue? Or I miss something?

**Comment by shiraji** [comment]
Did you read https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md#migrating-to-3x ?
If yes, and got the same error, then post minimum reproducable project as the issue template said.

**Comment by luna-vulpo** [comment]
No. I don't. Thx.
