### ISSUE TITLE
Program type already present: permissions.dispatcher.OnNeverAdkAgain

### ISSUE THREAD

**Issue by shaojin8864** [permissions-dispatcher/PermissionsDispatcher#484]
___

## Overview
this is my Project Level build.gradle
`buildscript {
    ext.kotlin_version = '1.2.41'

    ext.versions = [
            'kotlin': '1.2.41',
    ]
    repositories {
        maven { url "http://192.168.1.60:8081/repository/maven-public/" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
//        classpath 'com.antfortune.freeline:gradle:0.8.7'

        classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
    }
}

allprojects {
    repositories {
        maven { url "http://192.168.1.60:8081/repository/maven-public/" }
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.encoding = "UTF-8"
        }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}`
this is my Module Level build.gradle
`buildscript {
    ext.kotlin_version = '1.2.41'

    ext.versions = [
            'kotlin': '1.2.41',
    ]
    repositories {
        maven { url "http://192.168.1.60:8081/repository/maven-public/" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
//        classpath 'com.antfortune.freeline:gradle:0.8.7'

        classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
    }
}

allprojects {
    repositories {
        maven { url "http://192.168.1.60:8081/repository/maven-public/" }
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.encoding = "UTF-8"
        }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
`
### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

java 1.8 64bit
gradle 4.5
android studio 3.1.2

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by shaojin8864** [comment]
@hotchemi i use kotlin 1.2.41 ,but my colleague not work fine which don't use kotlin

**Comment by hotchemi** [comment]
@shaojin8864 seems there's no kapt or annotationProcessor word in your build file..please read README and sample again and try!

**Comment by shaojin8864** [comment]
sorry，the Module Level build.gradle file i upload it wrong, I upload again, please help me

**Comment by hotchemi** [comment]
please format

**Comment by shaojin8864** [comment]
@hotchemi i just update the code,please help me to have a look that build.gradle.i am a little worried.

**Comment by hotchemi** [comment]
How about changing repositories section like below?

```gradle
google()
jcenter()
maven {url ...}
```

**Comment by shaojin8864** [comment]
@hotchemi eh,i just config a nexus proxy that address is 192.168.1.60.the nexus agent the google() and jcenter()
