### ISSUE TITLE
Upload to Maven Central Repository

### ISSUE THREAD

**Issue by shiraji** [permissions-dispatcher/PermissionsDispatcher#485]
It's seems that we may need to upload our artifact to Maven Central is better idea. 

https://twitter.com/JakeWharton/status/1004745103292944384

Because if this tweet actually happens, Android default project would not contain `jcenter()` in build.gradle. We can still upload the artifact to jcenter, thou.

What do you think?

**Comment by hotchemi** [comment]
Umm, it's unofficial tweet and I'm not a huge fun of Maven Central actually(as it requires cumbersome procedure)🤔
Let's see what would happen after the incident, thx for heads up!
