### ISSUE TITLE
Conductor library support

### ISSUE THREAD

**Issue by TemMax** [permissions-dispatcher/PermissionsDispatcher#496]
[Conductor](https://github.com/bluelinelabs/Conductor) is a popular library that used as a replacing of fragments. Support for it will be so useful thing.

**Comment by hotchemi** [comment]
Seems it has getActivity so that you can integrate easily.

https://github.com/bluelinelabs/Conductor/blob/131589670f485bdd85a606d3a125af0b0ae1a77d/conductor/src/main/java/com/bluelinelabs/conductor/Controller.java#L287

Reopen if needed~

**Comment by hotchemi** [comment]
@Sar777 I thought you should annotate activity and call method in activity as usual. Isn't it possible? 👀 
If not we have to customize the library 🤔

**Comment by Sar777** [comment]
it isn't good idea for Single Activity apps :(

**Comment by Sar777** [comment]
Hello, I've added support for conductor. https://github.com/Sar777/PermissionsDispatcher/tree/feature/conductor

**Comment by hotchemi** [comment]
Oh, can you send us pull request? I'd like to take a look.

**Comment by hotchemi** [comment]
Prototype: https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/546

**Comment by hotchemi** [comment]
@TemMax @Sar777 what do you think about https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/574

**Comment by hotchemi** [comment]
PR is done
