### ISSUE TITLE
xiaomi 6  get permissions WRITE_EXTERNAL_STORAGE  error

### ISSUE THREAD

**Issue by rock8808** [permissions-dispatcher/PermissionsDispatcher#506]
xiaomi 6 no callback Error
![qq 20180802092303](https://user-images.githubusercontent.com/36020520/43568460-3227a4c4-9667-11e8-8040-70844b345107.png)

**Comment by hotchemi** [comment]
👀 Do you come up with any workaround?

**Comment by hotchemi** [comment]
If you don't use they library what kind of permission check code would work? 👀

**Comment by hotchemi** [comment]
let me close since no response for a while
