### ISSUE TITLE
All the annotations classes are not included in the package since 3.3.1

### ISSUE THREAD

**Issue by whataa** [permissions-dispatcher/PermissionsDispatcher#508]
## Overview

These classes exist in versions 3.2.0 and earlier. Didn't anyone point it out ? 
![image](https://user-images.githubusercontent.com/10238308/43627510-409771d4-9729-11e8-8d10-b2cac8296cc5.png)

**Comment by hotchemi** [comment]
We separated annotation module to make code loose coupled. Any issue because of it?

**Comment by whataa** [comment]
No issue, I just want to upgrade it. 
So, where is the annotation module and how can I import it? I do not see anything newer in the README.

**Comment by hotchemi** [comment]
Just updating version to 3.3.1 is supposed to be enough. if it doesn't work try clearing caches(Gradle, AS).

**Comment by mannodermaus** [comment]
If you really want to manually include the annotations, the artifact is called `permissionsdispatcher-annotation`. However, this should be a transitive dependency when you pull in `permissionsdispatcher`. Could you share your `build.gradle` file and how you pull in the library in the `dependencies` block? Also, do you use Jitpack? If so, please review the order in which the repositories are listed in your project, and make sure that `jcenter()` is _above_ the Jitpack declaration.

**Comment by whataa** [comment]
I already tried like that, it still doesn't work.

![image](https://user-images.githubusercontent.com/10238308/43635824-ddd14ed4-9742-11e8-8a65-cc8e8d4862c5.png)

### Step
1. ./gradlew clean
2. ./gradlew assembleDebug

**Comment by whataa** [comment]
I see, because I add `transitive false` for it. Thank you.

I suggest adding this to the README, maybe there exist others do it just like me.
