### ISSUE TITLE
如果权限被同意了,我在activity中该如何监听

### ISSUE THREAD

**Issue by clbDream** [permissions-dispatcher/PermissionsDispatcher#513]
刚才发现全部同意了权限会调用权限不再提示那个方法
 @OnNeverAskAgain(Manifest.permission.READ_CALENDAR, Manifest.permission.WRITE_CALENDAR, Manifest.permission.CAMERA)
    fun refusePermission() {
        toast("您后续可以在设置中心打开相应的权限哦!")
    }

**Comment by hotchemi** [comment]
Sorry we don't understand Chinese. Please open another issue in English if needed.
