### ISSUE TITLE
How do you listen to users if they agree to permissions

### ISSUE THREAD

**Issue by clbDream** [permissions-dispatcher/PermissionsDispatcher#515]
Do I need to manually judge myself in the @needspermission annotation

**Comment by hotchemi** [comment]
Sorry I don't understand..if user has granted permission `NeedsPermission` annotated method would be executed

**Comment by clbDream** [comment]
NeedsPermission annotation is not to apply for permission, you see if I need to write it this way

@NeedsPermission(Manifest.permission.READ_CALENDAR, Manifest.permission.WRITE_CALENDAR, Manifest.permission.CAMERA)
    fun requestPermission() {
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){
            return
        }
        when (SEND_TYPE) {
            0 -> {
                //发布图文
                startActivity(Intent(this,SendTextActivity::class.java))
            }
            1->{
                //发布视频
                startActivity(Intent(this,SendVideoActivity::class.java))
            }
            else -> {
            }
        }

    }
