### ISSUE TITLE
AAPT2 error.

### ISSUE THREAD

**Issue by enriquebautista** [permissions-dispatcher/PermissionsDispatcher#517]
LogCat:

../../.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/cd23fe25e0cfab62f395a43b9b256228/res/values/values.xml

error: resource android:attr/fontVariationSettings not found.
error: resource android:attr/ttcIndex not found.

**Comment by hotchemi** [comment]
are you using 4.0.0-alpha1? if you use appcompat please use 3.x.
