### ISSUE TITLE
support-v7 version

### ISSUE THREAD

**Issue by FlySelfLog** [permissions-dispatcher/PermissionsDispatcher#518]
```
dependencies {
implementation 'com.android.support:appcompat-v7:27.1.1'
implementation "com.github.hotchemi:permissionsdispatcher:3.3.1"
annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:3.3.1"
}
```

when syncing the gradle file, Android studio prompts error:
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.0.2. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:support-media-compat:27.0.2

I know it could be solved by using appcompat-v7:27.0.2, but I want to use appcompat-v7:27.1.1

**Comment by hotchemi** [comment]
Try

```
implementation('com.github.hotchemi:permissionsdispatcher') {
    exclude module: 'appcompat-v7'
}
```
