### ISSUE TITLE
FragmentPermissionDispatcher is not generated another fragment function on same package

### ISSUE THREAD

**Issue by rahmatrasyidi** [permissions-dispatcher/PermissionsDispatcher#520]
### Expected

- Generate FragmentA.readAndReceiveSmsWithPermissionCheck() and FragmentB.readAndReceiveSmsWithPermissionCheck() on same package

### Actual

- Only generate FragmentA.readAndReceiveSms()

### Environment

- PD 3.2.0 and PD Processor 3.3.1

**Comment by rahmatrasyidi** [comment]
@eyedol @punchdrunker @snkashis @egor-n @hotchemi

**Comment by hotchemi** [comment]
resolved?
