### ISSUE TITLE
I got a problem about supportLibary

### ISSUE THREAD

**Issue by weiweiForAndroid** [permissions-dispatcher/PermissionsDispatcher#528]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-alpha3] AndroidManifest.xml:22:18-91
is also present at [androidx.core:core:1.0.0-alpha3] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:17:5-64:19 to override.

**Comment by hotchemi** [comment]
If you're trying to use 4.x ver be sure to use 3.x 

https://github.com/permissions-dispatcher/PermissionsDispatcher#download
