### ISSUE TITLE
4.0.0 release?

### ISSUE THREAD

**Issue by giles-payne-d** [permissions-dispatcher/PermissionsDispatcher#531]
Any chance of a 4.0.0 release (without the alpha tag)? Would be really helpful for the androidx switch-over

**Comment by hotchemi** [comment]
oh thx for heads up. Aactually we're ready to release. Let me check issues again.

**Comment by hotchemi** [comment]
I'll release tonight

**Comment by giles-payne-d** [comment]
> I'll release tonight

Thanks!

**Comment by hotchemi** [comment]
🎉 https://github.com/permissions-dispatcher/PermissionsDispatcher/releases/tag/4.0.0
