### ISSUE TITLE
Miui 10 show the request dialog twice

### ISSUE THREAD

**Issue by HarveyLee1228** [permissions-dispatcher/PermissionsDispatcher#533]
When I request one permission,MIUI will show me the request dialog twice .When I clicked the nagative button ,it will show more than twice ,I dont know how to avoid it .I am using version 3.3.1

**Comment by hotchemi** [comment]
If you're not using library you can avoid the problem?

**Comment by HarveyLee1228** [comment]
> If you're not using library you can avoid the problem?
Yes,I didn't get this problem before I changed my code to this library ,and I test another phone(Huawei),this library works fine .So this problem happens on Miui.

**Comment by hotchemi** [comment]
Can I get a correct code that works correctly? 🤔 

Currently we have dedicated code for Xiaomi but other than that it's supposed to be ok.. 🤔 

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/1564313f8b253685dc7189b0fbb31a42b2e86796/library/src/main/java/permissions/dispatcher/PermissionUtils.java#L94

**Comment by HarveyLee1228** [comment]
> Can I get a correct code that works correctly? 
> 
> Currently we have dedicated code for Xiaomi but other than that it's supposed to be ok.. 
> 
> [PermissionsDispatcher/library/src/main/java/permissions/dispatcher/PermissionUtils.java](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/1564313f8b253685dc7189b0fbb31a42b2e86796/library/src/main/java/permissions/dispatcher/PermissionUtils.java#L94)
> 
> Line 94 in [1564313](/permissions-dispatcher/PermissionsDispatcher/commit/1564313f8b253685dc7189b0fbb31a42b2e86796)
> 
>  private static boolean hasSelfPermission(Context context, String permission) {



> Can I get a correct code that works correctly? 
> 
> Currently we have dedicated code for Xiaomi but other than that it's supposed to be ok.. 
> 
> [PermissionsDispatcher/library/src/main/java/permissions/dispatcher/PermissionUtils.java](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/1564313f8b253685dc7189b0fbb31a42b2e86796/library/src/main/java/permissions/dispatcher/PermissionUtils.java#L94)
> 
> Line 94 in [1564313](/permissions-dispatcher/PermissionsDispatcher/commit/1564313f8b253685dc7189b0fbb31a42b2e86796)
> 
>  private static boolean hasSelfPermission(Context context, String permission) {

actually version 2.2.1 works correctly on Miui 10,I found this solution in the closed issue history. I suggest not to use the dedicated code for Miui.

**Comment by hotchemi** [comment]
You mean `"Xiaomi".equalsIgnoreCase(Build.MANUFACTURER)` returns true in Miui device? 👀 Could you possibly test with `PermissionUtils.java`? 🙇

**Comment by ludovicroland** [comment]
@hotchemi : I guess it's normal that the `"Xiaomi".equalsIgnoreCase(Build.MANUFACTURER)` returns true on the Miui device. Miui is developed  by Xiaomi. So I guess @HarveyLee1228 is working on a Xiaomi phone. Right ?

**Comment by Spikoss** [comment]
@HarveyLee1228  
when I do not use this library,my xiaomi phone can also show a permission dialog while i don't check permission in code,just in  AndroidManifest.xml , 
so i think that because MIUI System has enclosure it, just as it enclosures Toast .

**Comment by hotchemi** [comment]
so does nothing when running on MIUI 10 is the answer?
Then I'd like to close the issue because it's out of the scope haha 😅

**Comment by she246** [comment]
I meet the same question，how to resolve that？ use version 2.2.1？

**Comment by hotchemi** [comment]
@she246 @HarveyLee1228 @ludovicroland @Spikoss https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/533#issuecomment-438642578 what do you think?

**Comment by hotchemi** [comment]
Let us know your opinion https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/544

**Comment by hc1028** [comment]
Miui 10 show the request dialog twice because ：
`AppOpsManagerCompat.noteOp(context, permissionToOp, Process.myUid(), context.getPackageName())`
I modified the source code
`   private static boolean hasSelfPermission(Context context, String permission) {
//        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && "Xiaomi".equalsIgnoreCase(Build.MANUFACTURER)) {
//            return hasSelfPermissionForXiaomi(context, permission);
//        }
        try {
            return PermissionChecker.checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED;
        } catch (RuntimeException t) {
            return false;
        }
    }`
MIUI may have modified the Android source code

**Comment by hc1028** [comment]
Miui 10 show the request dialog twice because ：
AppOpsManagerCompat.noteOp(context, permissionToOp, Process.myUid(), context.getPackageName())
I modified the source code
![image](https://user-images.githubusercontent.com/16715125/49197170-d6f21c00-f3c8-11e8-9fa9-4c17e3aa7693.png)

MIUI may have modified the Android source code

**Comment by hotchemi** [comment]
Oh thank you! so https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/544 would solve the problem may be?😅

**Comment by hotchemi** [comment]
Do you think https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/548 would address the issue?

**Comment by hotchemi** [comment]
I suppose 4.1.0 solves the issue. Check it out.
https://github.com/permissions-dispatcher/PermissionsDispatcher/releases/tag/4.1.0
