### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by wangjing71** [permissions-dispatcher/PermissionsDispatcher#539]
when i use :
    implementation 'com.github.hotchemi:permissionsdispatcher:4.0.0'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:4.0.0'
error:
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-20:19 to override.

then i use:
compile 'com.github.hotchemi:permissionsdispatcher:2.3.1'
annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.1'
it is work.

**Comment by hotchemi** [comment]
@wangjing71 I suppose because you're using appcompat. 4.x only supports androidx package so upgrade to use androidx or use 3.x.
