### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by ArthurCL** [permissions-dispatcher/PermissionsDispatcher#541]
implementation "com.github.hotchemi:permissionsdispatcher:4.0.0"
    annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:4.0.0"

添加这两句后    工程直接报错了     编译不通过

**Comment by hotchemi** [comment]
Sorry we don't understand Chinese 😓

**Comment by hotchemi** [comment]
reopen if needed
