### ISSUE TITLE
I want to give up using in my project because of xiaomi phone

### ISSUE THREAD

**Issue by she246** [permissions-dispatcher/PermissionsDispatcher#542]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by hotchemi** [comment]
@she246 what's your request?
