### ISSUE TITLE
compilation not happening for fragments in kotlin

### ISSUE THREAD

**Issue by aravindvogo** [permissions-dispatcher/PermissionsDispatcher#543]
I am trying to implement the permission dispatcher in fragment by using kotlin language ..
when i use onRequestPermissionsResult ,it is giving error saying that Generated onRequestPermission method not called. but I have called  anyway

Please check this

` override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        onRequestPermissionsResult(requestCode,grantResults)
    }`

**Comment by hotchemi** [comment]
@aravindvogo you mean lint error?

Ref:
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/3d063cc27f27d95bb4c90b814f48707e806ea68b/sample-kotlin/src/main/kotlin/permissions/dispatcher/samplekotlin/MainActivity.kt#L33

**Comment by susemi99** [comment]
I have same error. 

<img width="931" alt="screenshot" src="https://user-images.githubusercontent.com/1233318/48927967-ffd46600-ef1d-11e8-8443-8e6628b93c8e.png">

**Comment by hotchemi** [comment]
@susemi99 seems you're not using kapt? could you try bundled `sample-kotlin` module?

**Comment by hotchemi** [comment]
@aravindvogo as there're few info we'll close the issue. reopen if needed with more detail.
