### ISSUE TITLE
[Proposal]Drop Xiaomi support?

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#544]
to @permissions-dispatcher/maintainers and users

## Overview

We've been suffering from Xiaomi [issues](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues?q=is%3Aissue+is%3Aopen+label%3Axiaomi) in a past few years. There's no official document, reference and seems like they've changed permission related behavior without any announcement🤔

And according to https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/533#issuecomment-438170843 the latest MIUI has a system that automatically handles permission dialog on system side👀Not it's a good time to drop Xiaomi handling code from our library? What do you think?

From my point of view:

#### Props

- Make it easier to maintain
- Simpler logic, less method counts

#### Cons

- User has to enclose workaround for older MIUI device?

**Comment by shiraji** [comment]
Developers who have to handle newest MIUI system should get the same result with us. I wonder how they fix the problem...

**Comment by hotchemi** [comment]
done 😇

**Comment by hotchemi** [comment]
@wangxinghe do you have any insights(sorry to mention you suddenly since I've just seen you gave a star to the library:D)? 🙇
