### ISSUE TITLE
Merging Errors: Error: tools:replace specified at line:9 for attribute android:appComponentFactory, but no new value specified app main manifest (this file), line 8 Error: Validation failed, exiting app main manifest (this file)

### ISSUE THREAD

**Issue by leichentao09** [permissions-dispatcher/PermissionsDispatcher#550]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by hotchemi** [comment]
See https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/539
