### ISSUE TITLE
I want drop xiaomi support without androidx?

### ISSUE THREAD

**Issue by meixililu** [permissions-dispatcher/PermissionsDispatcher#552]
I want drop xiaomi support without androidx?

**Comment by hotchemi** [comment]
Let us check it's possible or not. But basically we recommend to upgrade to 4.x.

**Comment by meixililu** [comment]
can't upgrade now,other module do not upgrade to 4.x. And I try to download the source code,import to my project,but faile with some problem.

**Comment by hotchemi** [comment]
OK.

**Comment by hotchemi** [comment]
You can use https://github.com/permissions-dispatcher/PermissionsDispatcher/tree/3.3.2.

**Comment by meixililu** [comment]
Thank u.
