### ISSUE TITLE
Change Maven coordinates

### ISSUE THREAD

**Issue by mannodermaus** [permissions-dispatcher/PermissionsDispatcher#560]
We've all seen [the recent article about malicious dependencies](https://blog.autsoft.hu/a-confusing-dependency/). Basically, it's very trivial to upload malicious code to `jcenter()`, which is why it should be at the very bottom of any project's `repositories` block. For libraries that rely on [Jitpack](https://jitpack.io/), it's important to list that repository above JCenter.

PermissionsDispatcher lives in the `com.github.hotchemi` namespace, and we've had issues in the past where people accidentally pulled in from Jitpack, not the JCenter that we provide our artifacts to. (Background: Jitpack will pick up on any group ID starting with `com.github`, which is a mistake for PD, but Jitpack doesn't know that.) Since this would mean that PD users _do_ need to specify `jcenter()` first, I would like to propose a change in Maven coordinates going forward to keep everybody safe.

**Comment by hotchemi** [comment]
@mannodermaus thank you so much! I basically agree for the proposal:D Could you possibly work on that?

**Comment by mannodermaus** [comment]
I'll try to allocate some time this weekend, sure. Now, what do you guys propose the new coordinates should be? Since we don't own any domain for PD, we'd have to find another solution...

**Comment by mannodermaus** [comment]
How do you feel about these artifacts?

|Old|New (1)|New (2)|
|---|---|---|
|`com.github.hotchemi:permissionsdispatcher`|`org.permissions.dispatcher:library`|`org.pd:permissionsdispatcher`|
|`com.github.hotchemi:permissionsdispatcher-processor`|`org.permissions.dispatcher:processor`|`org.pd:permissionsdispatcher-processor`|
|`com.github.hotchemi:permissionsdispatcher-annotation`|`org.permissions.dispatcher:annotation`|`org.pd:permissionsdispatcher-annotation`|

I prefer the first proposal, it looks more balanced. Also, what do we do about imports? Do we leave the packages where they are now?

**Comment by hotchemi** [comment]
LGTM! Seems we have to contact bintray support team so let me handle the issue
https://stackoverflow.com/q/34756204

**Comment by hotchemi** [comment]
Created new maven repo
https://bintray.com/hotchemi/org.permissionsdispatcher

**Comment by hotchemi** [comment]
We're going to release new artifact after https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/562 merged!
