### ISSUE TITLE
xiaomi show request dialog twice,version 4.1.0

### ISSUE THREAD

**Issue by lilipu1** [permissions-dispatcher/PermissionsDispatcher#563]
## Environment

- version 4.1.0 
- xiaomi8 & xiaomi Mix2s

**Comment by hotchemi** [comment]
we've already removed Xiaomi specific code from 4.1.0 so that we recommend user to define a workaround on your side. See https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/544
