### ISSUE TITLE
Unable to resolve version 4.2.0 in jitpack

### ISSUE THREAD

**Issue by kenshin171** [permissions-dispatcher/PermissionsDispatcher#575]
___

## Overview

- Getting an error during build phase of my android project. Screenshot below describes the issue. Did not have this issue with versions 4.0.0 and 4.1.0. Only seems to happen on 4.2.0

<img width="1290" alt="screenshot 2018-12-26 at 11 13 55 am" src="https://user-images.githubusercontent.com/6202427/50430793-139a3000-0901-11e9-91e8-bf3f9444b2c1.png">

### Expected

- Able to build successfully.

### Actual

- Getting `Could not resolve com.github.hotchemi:permissionsdispatcher-processor:4.2.0.` due to `status code 401 from server: Unauthorized`

## Environment

- Which library version are you using? **4.2.0**
- On which devices do you observe the issue? **no device needed**

## Reproducible steps
Do a build of the android project

**Comment by hotchemi** [comment]
We've changed groupId to `org.permissionsdispatcher`, check changelog https://github.com/permissions-dispatcher/PermissionsDispatcher/releases/tag/4.2.0

**Comment by kenshin171** [comment]
Ahhhh ok sorry my bad

**Comment by ray-pixar** [comment]
please update your change in the main page of github
