### ISSUE TITLE
kotlin无效

### ISSUE THREAD

**Issue by RuoYuHoney** [permissions-dispatcher/PermissionsDispatcher#582]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by hotchemi** [comment]
We don't understand Chinese, please reopen after editing the title and write description.
