### ISSUE TITLE
xiaomi phone permission exception（permission request success，create file fail(permission denied)）

### ISSUE THREAD

**Issue by zwping** [permissions-dispatcher/PermissionsDispatcher#583]
apply for permission on xiaomi phone,the permission application is successful, but the file create fail,log reminder permission denied

open app settings, `acceess and change files on internal storage`  is success

phone: 
	mix3(miui:10.2 android:P)
	mix2(miui:10.2 android:O)

use:
<pre> 
    implementation("com.github.hotchemi:permissionsdispatcher:3.3.2") {
        // if you don't use android.app.Fragment you can exclude support for them
        exclude module: "support-v13"
    }

    kapt "com.github.hotchemi:permissionsdispatcher-processor:3.3.2" </pre>

**Comment by hotchemi** [comment]
How about 4.x?

**Comment by hotchemi** [comment]
reopen if needed 🐗

**Comment by zwping** [comment]
sorry, due to jet lag(in china), no first time debug

just used separately permissions dispatcher 3.3.2/4.3.0 debug from new project, xiaomi phone the are still bug

**Comment by hotchemi** [comment]
I think in 4.3.0 there's no Xiaomi dedicated code so that I wonder bug is on OS side? 🤔 Do you know what's the valid code which works on the device? 👀

**Comment by zwping** [comment]
i don't know, i'm android small white....

**Comment by zwping** [comment]
a new [framework](https://github.com/yanzhenjie/AndPermission) has been found, he was dev by the chinese, he can solve the xiaomi bug

you can also go and see it.
