### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by JoyHong** [permissions-dispatcher/PermissionsDispatcher#585]
Could not GET 'https://jitpack.io/com/github/hotchemi/permissionsdispatcher-processor/4.2.0/permissionsdispatcher-processor-4.2.0.pom'. Received status code 401 from server: Unauthorized

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'com.tencent.bugly:symtabfileuploader:1.3.8'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath "io.realm:realm-gradle-plugin:1.2.0"
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.6.0'
        classpath 'me.tatarka:gradle-retrolambda:3.6.0'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://maven.google.com' }
        maven { url 'http://dl.bintray.com/optimizely/optimizely' }
        maven { url "https://jitpack.io" }
        maven {
            name "Tapjoy's maven repo"
            url "https://tapjoy.bintray.com/maven"
        }
    }
}

**Comment by hotchemi** [comment]
artifactId has been changed, make sure to use `org.permissionsdispatcher`.
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/CHANGELOG.md
