### ISSUE TITLE
[question] UsbManager.EXTRA_PERMISSION_GRANTED

### ISSUE THREAD

**Issue by tim4dev** [permissions-dispatcher/PermissionsDispatcher#587]
This is not an issue.
Is it possible to use the library to request rights to UsbManager.EXTRA_PERMISSION_GRANTED.
The problem is that there is no equivalent for Manifest.

i'm talking about:
[Obtain permission to communicate with a device](https://developer.android.com/guide/topics/connectivity/usb/host#permission-d)

**Comment by hotchemi** [comment]
I'm not sure about UsbManager but do you need to ask a request for user?
