### ISSUE TITLE
[Question] Detect annotation kind if few defined for a methon

### ISSUE THREAD

**Issue by neooleg** [permissions-dispatcher/PermissionsDispatcher#589]
Hi Team,

Thanks a lot to amazing product!

Does this possible to understand which action user did if the following solution implemented?

```
    @NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    @OnPermissionDenied(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    @OnNeverAskAgain(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    public void writeStorage() {
        // Detect a kind of annotation to handle
    }
```

Thanks in advance!

**Comment by hotchemi** [comment]
@neooleg Hi there now we don't support as such and no plan to do that~. We recommend to separate definitions to make them declarative~.

**Comment by neooleg** [comment]
Got it, thanks for a quick answer
