### ISSUE TITLE
Do not call requestPermissions if permission was already denied permanently

### ISSUE THREAD

**Issue by WonderCsabo** [permissions-dispatcher/PermissionsDispatcher#590]
## Overview

The library ask for permissions even if the user permanently denied it before (checked "Do not ask again"). This adds an unnecessary call, and also notifies the app about a user action which is not happening (the permission dialog is not shown actually). 

### Expected

If we detekt the user already denied the permission with never ask again, we should not call `requestPermissions()`.

### Actual

Currently we always call `requestPermissions()`, regardless the user denied it permanetly before or not.

###  Pseudo solution
```kotlin
fun WelcomeScreenFragment.welcomeButtonClickedWithPermissionCheck() {
    if (PermissionUtils.hasSelfPermissions(this.requireActivity(),
                    *PERMISSION_WELCOMEBUTTONCLICKED)) {
        welcomeButtonClicked()
    } else {
        if (PermissionUtils.shouldShowRequestPermissionRationale(this,
                        *PERMISSION_WELCOMEBUTTONCLICKED)) {
            this.requestPermissions(PERMISSION_WELCOMEBUTTONCLICKED, REQUEST_WELCOMEBUTTONCLICKED)
        }
    }
}
```

**Comment by hotchemi** [comment]
Thank you for your suggestion and that makes a lot of sense! Would you mind open a PR? 👀

**Comment by WonderCsabo** [comment]
I try to find the time to do it!

**Comment by isabsent** [comment]
Does this issue exist for Kotlin only or Java is suffered to it too?

**Comment by WonderCsabo** [comment]
I experienced it using Java. I think this issue is language independent.

**Comment by kaushalyap** [comment]
actually if permission is denied permanently, app should allow user to go to settings and rectify it, since [it is good UX](https://uxplanet.org/mobile-ux-design-the-right-ways-to-ask-users-for-permissions-6cdd9ab25c27)

**Comment by hotchemi** [comment]
let us close the issue as:

- AFAIK there's no API that we can get the result without onRequestPermissionsResult(and it's deprecated)
- it's been a long since the issue was opened.

we're still welcome for the PR.
