### ISSUE TITLE
Error: cannot find symbol in Android X with 4.3.0

### ISSUE THREAD

**Issue by PankajSavaliya** [permissions-dispatcher/PermissionsDispatcher#597]
Geeting **Error** while Migrate to **Android X**

symbol:   variable ProfileFragment**PermissionsDispatcher**
location: class ProfileFragment

 xxxPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);

Also not generated 

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
24 errors

**Comment by hotchemi** [comment]
- Could you try clearing gradle and AS caches?
- Could you try on our sample module? https://github.com/permissions-dispatcher/PermissionsDispatcher/tree/master/sample

We haven't gotten enough info for the issue so let me close for the time being and reopen if needed 🙇
