### ISSUE TITLE
Support Kapt incremental annotation processors

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#600]
https://youtrack.jetbrains.com/issue/KT-23880

**Comment by technoir42** [comment]
@hotchemi are you already working on this? I have a prototype locally but waiting for https://github.com/square/kotlinpoet/pull/680.

**Comment by hotchemi** [comment]
@technoir42 oh thx! Can we see PR or diff patch file? 🙇

**Comment by rishabh876** [comment]
> @hotchemi are you working on this? I have a prototype locally but waiting for [square/kotlinpoet#680](https://github.com/square/kotlinpoet/pull/680).

As this is now merged, any update on this issue? @technoir42

**Comment by hotchemi** [comment]
Let me check!

**Comment by technoir42** [comment]
Sorry, got busy looking for a job. Luckily, a version of KotlinPoet that we needed was released so I've opened 3 PRs with my implementation.

**Comment by hotchemi** [comment]
Thank you, gonna check later.
