### ISSUE TITLE
Nullable params have wrong type with Kotlin

### ISSUE THREAD

**Issue by m-i-k-e-e** [permissions-dispatcher/PermissionsDispatcher#603]
## FAQs

 
___

## Overview
Hello,

It looks like Nullable Double parameters are wrongly resolved.

### Expected

Parameters to be resolved as kotlin.Double?

`fun setupMap(zoomLevel: Double, latitude: Double?, longitude: Double)`
`fun TrackedMapFragment.setupMapWithPermissionCheck(
zoomLevel: Double,latitude: Double?, longitude: Double)`

### Actual

Parameters are resolved as java.lang.Double?

`fun setupMap(zoomLevel: Double, latitude: Double?, longitude: Double)`
`fun TrackedMapFragment.setupMapWithPermissionCheck(
    zoomLevel: Double,
    latitude: java.lang.Double?,
    longitude: Double
) `

## Environment

kapt "org.permissionsdispatcher:permissionsdispatcher-processor:4.3.0"
implementation 'org.permissionsdispatcher:permissionsdispatcher:4.3.0'

**Comment by hotchemi** [comment]
Thx for your report. Can I suppose the problem here is `Double?` is converted to `java.lang.Double?`, am I correct?

**Comment by m-i-k-e-e** [comment]
Exactly. It creates errors at compile time as for some reasons, Kotlin.Double is not the same as Java.lang.Double. 
But it only happens with nullable values

**Comment by hotchemi** [comment]
I see. I think this is due to KotlinPoet.. 🤔

**Comment by alifhasnain** [comment]
Still having an issue with nullable `Long` type. Generated code is using `java.lang.Long` instead of` kotlin.Long`.
