### ISSUE TITLE
Android Q: Location Permissions

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#604]
https://android-developers.googleblog.com/2019/03/introducing-android-q-beta.html
https://joebirch.co/2019/03/18/exploring-android-q-location-permissions/

**Comment by mannodermaus** [comment]
Are there any immediate action points for us regarding Android Q and location permissions? As far as I understand it, there's one more permission for background-related usage, but that shouldn't require any work from our side, right?

Now, the overhaul and deprecation of `*_EXTERNAL_STORAGE`, on the other hand...

**Comment by hotchemi** [comment]
sorry for the late reply! Let me check just in case and probably it'd be kind to prepare example code for that?😃

**Comment by hotchemi** [comment]
After moving around seems there's no need to address. Let me close the issue for the time being🙇
