### ISSUE TITLE
 Does this library support chinese brands such as Xiaomi, Huawei?

### ISSUE THREAD

**Issue by zhangshen147** [permissions-dispatcher/PermissionsDispatcher#616]

**Comment by hotchemi** [comment]
Hi, if Xiaomi, Huawei? doesn't have unique mechanism we can say we're supporting. Previously we added dedicated implementation for Xiaomi but we removed a few months ago for some reason. Check https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/544 out if you're interested in!
