### ISSUE TITLE
How to pop up prompts at once instead of popping up each item

### ISSUE THREAD

**Issue by thsseek** [permissions-dispatcher/PermissionsDispatcher#618]
```
@NeedsPermission({Manifest.permission.READ_PHONE_STATE, Manifest.permission
            .READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest
            .permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.CAMERA, Manifest.permission.READ_CONTACTS, Manifest.permission
            .RECORD_AUDIO})
    public void requestPermission() {

}
```

<img width="463" alt="屏幕快照 2019-05-20 下午5 38 19" src="https://user-images.githubusercontent.com/14950738/58012701-a42f1200-7b27-11e9-8f0b-72d943296c47.png">
<img width="461" alt="屏幕快照 2019-05-20 下午5 38 12" src="https://user-images.githubusercontent.com/14950738/58012797-dc365500-7b27-11e9-9cba-0810c574a28a.png">

**Comment by hotchemi** [comment]
I guess you can't do that even without our library since we just delegate the exact requesting permission work to Android framework.
