### ISSUE TITLE
Kotlin generation doesn't keep ByteArray

### ISSUE THREAD

**Issue by artnest** [permissions-dispatcher/PermissionsDispatcher#619]
## Overview

`@NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
fun saveBytes(bytes: ByteArray) {
    ...
}`

### Expected

`fun Fragment.saveBytesWithPermissionCheck(bytes: ByteArray) {
    ...
}`

I expect Kotlin ByteArray type as in the original function, which conforms to `byte[]` in Java.

### Actual

`fun Fragment.saveBytesWithPermissionCheck(bytes: Array<Byte>) {
    ...
}`

## Environment

- Which library version are you using?
4.3.1

**Comment by hotchemi** [comment]
Same as https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/599
