### ISSUE TITLE
Kotlin generation doesn't keep Array<kotlin.Byte>

### ISSUE THREAD

**Issue by artnest** [permissions-dispatcher/PermissionsDispatcher#620]
## Overview

`@NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
fun saveBytes(bytes: Array<Byte>) {
    ...
}`

### Expected

`fun Fragment.saveBytesWithPermissionCheck(bytes: Array<kotlin.Byte>) {
    ...
}`

I expect both Kotlin Byte type.

### Actual

`fun Fragment.saveBytesWithPermissionCheck(bytes: Array<java.lang.Byte>) {
    ...
}`

## Environment

- Which library version are you using?
4.3.1

**Comment by artnest** [comment]
Here is a workaround:
`fun Fragment.saveBytesWithPermissionCheck(bytes: Array<java.lang.Byte>) { ... }

// bytes is a Kotlin ByteArray
var byteArray = arrayOf<java.lang.Byte>()
bytes.forEach { byte ->
    byteArray += java.lang.Byte(byte)
}
saveBytesWithPermissionCheck(byteArray)

@NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
fun saveBill(bytes: Array<java.lang.Byte>) {
    val byteArray = ByteArray(bytes.size) { index -> bytes[index].toByte() }
    // now use you can use byteArray, which is Kotlin ByteArray
}`

**Comment by hotchemi** [comment]
Same as https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/599
