### ISSUE TITLE
failed to import 3.x

### ISSUE THREAD

**Issue by JarenFeng** [permissions-dispatcher/PermissionsDispatcher#621]
___

## Overview

Can't import permissionsDispatcher 3.x.

And i found nothing on [snapshot](http://oss.jfrog.org/artifactory/oss-snapshot-local/org/permissionsdispatcher/)

![image](https://user-images.githubusercontent.com/12081818/58853860-285bca80-86ce-11e9-9325-c33b026b07ac.png)
![image](https://user-images.githubusercontent.com/12081818/58853897-4e816a80-86ce-11e9-9b47-4041e5b60278.png)
![image](https://user-images.githubusercontent.com/12081818/58853907-57723c00-86ce-11e9-9998-21f499a62ee5.png)
![image](https://user-images.githubusercontent.com/12081818/58853920-61943a80-86ce-11e9-9697-68d1be1927e6.png)

**Comment by hotchemi** [comment]
We've changed groupId from v4. Please use `com.github.hotchemi` as groupid.

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md#change-maven-groupid
