### ISSUE TITLE
[Question] - Fragment Documantation

### ISSUE THREAD

**Issue by TurKurT656** [permissions-dispatcher/PermissionsDispatcher#624]
Is there any doc to show how to use this lib with fragments?
i'm using android x library

**Comment by hotchemi** [comment]
There's no official doc but you can use the library as same as on Activity :D

JFYI: the article may help you: http://mobiledevhub.com/2017/11/24/android-fundamentals-requesting-permissions-in-fragment/

**Comment by TurKurT656** [comment]
Ty for quick answer.
but in there what is PermissionFragmentPermissionsDispatcher ?
i coudnt find that

**Comment by hotchemi** [comment]
it will be generated at compile time. Try our sample module first of all to figure out the usage~

**Comment by TurKurT656** [comment]
yes i saw the sample folder but there is only activity runtime permission

but in my fragment:

@RuntimePermissions
class AddPostFragment : androidx.fragment.app.Fragment() {

    @NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    fun openCamera() {
    }

   
}

it does not generate AddPostFragmentPermisionDispatcher class

**Comment by hotchemi** [comment]
Check our sample module, especially around gradle.

https://github.com/permissions-dispatcher/PermissionsDispatcher#installation
