### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by czl0325** [permissions-dispatcher/PermissionsDispatcher#630]
implementation "org.permissionsdispatcher:permissionsdispatcher:4.3.1"
kapt "org.permissionsdispatcher:permissionsdispatcher-processor:4.3.1"

build error

<img width="1328" alt="屏幕快照 2019-06-27 下午7 00 59" src="https://user-images.githubusercontent.com/2100549/60261372-494ebe80-990e-11e9-82cf-98bf8c76a4c9.png">

<img width="1327" alt="屏幕快照 2019-06-27 下午7 01 18" src="https://user-images.githubusercontent.com/2100549/60261380-4eac0900-990e-11e9-96e5-31589a466293.png">

**Comment by mannodermaus** [comment]
Please post the entire log

**Comment by hotchemi** [comment]
FYI: if you're not using androidx please use 3.x version.

**Comment by czl0325** [comment]
what is 3.x version.   address??

**Comment by mannodermaus** [comment]
```
implementation "org.github.hotchemi:permissionsdispatcher:3.3.2"
kapt "org.github.hotchemi:permissionsdispatcher-processor:3.3.2"
```

@hotchemi-san, do we still advertise the 3.x coordinates for non-AndroidX users anywhere?

**Comment by hotchemi** [comment]
we do have but may need to emphasize more🤔
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/README.md#installation
