### ISSUE TITLE
Some Xiaomi phone is not support.

### ISSUE THREAD

**Issue by ZYRzyr** [permissions-dispatcher/PermissionsDispatcher#633]
## FAQs

 
___

## Overview

After check `Don't ask again`  and deny the permission,  then accept the permission by manual(in 
phone's settings) is invalided.

### Expected
The permission should be granted.

### Actual

The permission is still denied.

## Environment
- Which library version are you using?
  4.5.0
- On which devices do you observe the issue?
  Xiaomi 8 and MIUI 10.3.3

## Reproducible steps

1.I check `Don't ask again`  and deny the permission.
2.Go `Settings` and accept the permission by manual. 
3.Back to app, the permission is still denied.

**Maybe it's Xiaomi system bug ?**

**Comment by hotchemi** [comment]
We've dropped Xiaomi support from 4.2.0 because we heard in latest versions MIUI started to behave same as plain Android framework itself. Can you check how it goes without library?

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/CHANGELOG.md

**Comment by ZYRzyr** [comment]
It's phone's bug.Use `ContextCompat.checkSelfPermission` is still reproduce.

**Comment by hotchemi** [comment]
Thank you for the clarification. Crazy...
