### ISSUE TITLE
Android 10 permissions

### ISSUE THREAD

**Issue by zouxianbincc** [permissions-dispatcher/PermissionsDispatcher#636]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by zouxianbincc** [comment]
Hello! How to adapt to Android 10 permissions？

**Comment by hotchemi** [comment]
Have you found any issues? Let us know then but I thought we can use the library on Android10.

**Comment by hotchemi** [comment]
@zouxianbincc let me know if you found some issues, thx!
