### ISSUE TITLE
how to apply for permission again when the user refuses to forbid access?

### ISSUE THREAD

**Issue by fadedHYC** [permissions-dispatcher/PermissionsDispatcher#641]
Hello, how to apply for permission again when the user refuses to forbid access?

**Comment by hotchemi** [comment]
if you're talking about "never ask again" checkbox you can use `OnNeverAskAgain` annotation to hook the event and navigating the user to system setting page is recommended I guess.

**Comment by fadedHYC** [comment]
But when I returned to the APP from the Settings page, I did not call back OnShowRationale () or NeedsPermission ().I want to call OnShowRationale () or NeedsPermission () or onPermissionDenied () when I return to the APP from the Settings page. Is there any method?




------------------ 原始邮件 ------------------
发件人: "Shintaro Katafuchi"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 晚上6:43
收件人: "permissions-dispatcher/PermissionsDispatcher"<PermissionsDispatcher@noreply.github.com>;
抄送: "恢恢黑夜"<1339868776@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [permissions-dispatcher/PermissionsDispatcher] how to apply forpermission again when the user refuses to forbid access? (#641)




Closed #641.

**Comment by hotchemi** [comment]
Please take a look the lib's usage again, we don't provide such kind of callback.
https://github.com/permissions-dispatcher/PermissionsDispatcher#1-attach-annotations

**Comment by fadedHYC** [comment]
Ok, thank you for your reply






------------------ 原始邮件 ------------------
发件人: "Shintaro Katafuchi"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 晚上10:45
收件人: "permissions-dispatcher/PermissionsDispatcher"<PermissionsDispatcher@noreply.github.com>;
抄送: "恢恢黑夜"<1339868776@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [permissions-dispatcher/PermissionsDispatcher] how to apply forpermission again when the user refuses to forbid access? (#641)




Please take a look the lib's usage again, we don't provide such kind of callback.
 https://github.com/permissions-dispatcher/PermissionsDispatcher#1-attach-annotations

**Comment by fadedHYC** [comment]
"REQUEST_INSTALL_PACKAGES"


Hello, how do I request installation permission?



This is my code.















Permissions have been granted, but not to install apk


------------------ 原始邮件 ------------------
发件人: "Shintaro Katafuchi"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 晚上10:45
收件人: "permissions-dispatcher/PermissionsDispatcher"<PermissionsDispatcher@noreply.github.com>;
抄送: "恢恢黑夜"<1339868776@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [permissions-dispatcher/PermissionsDispatcher] how to apply forpermission again when the user refuses to forbid access? (#641)




Please take a look the lib's usage again, we don't provide such kind of callback.
 https://github.com/permissions-dispatcher/PermissionsDispatcher#1-attach-annotations

**Comment by hotchemi** [comment]
@fadedHYC could you elaborate the issue and expected behaviour?

**Comment by fadedHYC** [comment]
I want to download the apk file in my app and install apk. How to apply for apk installation permission



---Original---

**Comment by kenargo** [comment]
REQUEST_INSTALL_PACKAGES is a new permission in Anroid O and above that allows apps to download and install APKs.

Is there plans to support this permission?
