### ISSUE TITLE
Generated kotlin files still use Java collections

### ISSUE THREAD

**Issue by kanat** [permissions-dispatcher/PermissionsDispatcher#642]
## Overview

I use kotlin in combination with kapt.

Suppose you've got some function below:
```kotlin
class SomeActivity : AppCompatActivity() {
    @NeedsPermission(CAMERA, RECORD_AUDIO)
    fun doWork(values: kotlin.collections.Set<kotlin.String>) {
        ...
    }
}
```

The `SomeActivityPermissionsDispatcher.kt` will be generated, but with different input type in the function:
```kotlin
fun SomeActivity.doWorkWithPermissionCheck(values: java.util.Set<java.lang.String>) {
    ...
}
```

### Expected

- `kotlin.collections.*` collections are used in generated files

### Actual

- `java.util.*` collections are used in generated files

## Environment

`implementation 'org.permissionsdispatcher:permissionsdispatcher:4.5.0'`
`kapt 'org.permissionsdispatcher:permissionsdispatcher-processor:4.5.0'`

**Comment by hotchemi** [comment]
thank you! this originates from kotlinpoet seemingly and we have a workaround method to address similar issue. Would you mind send a PR?

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/f9175b1ec883c054750783e71d1992a29bd05a49/processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt#L122

**Comment by kanat** [comment]
> thank you! this originates from kotlinpoet seemingly and we have a workaround method to address similar issue. Would you mind send a PR?
> 
> https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/f9175b1ec883c054750783e71d1992a29bd05a49/processor/src/main/kotlin/permissions/dispatcher/processor/util/Extensions.kt#L122

Thanks for navigating me to problematic point. Please, check the PR.
