### ISSUE TITLE
investigation: Android 11 permission changes

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#661]
We are going to investigate what we can/should do for the upcoming changes.

ref: https://developer.android.com/preview/privacy/permissions

**Comment by mannodermaus** [comment]
There may be some changes required for the background location permission. I am not familiar with the Android 10 model, but reading Joe Birch's article on what's new and upcoming in R, it looks like there have to be two separate requests for this particular permission. First, you ask for either Fine or Coarse permission and when granted, you ask again for the background permission. I have not validated this yet, but apparently the permission dialog would not show at all if you requested both at the same time. Users could probably have two annotated methods to do this, but maybe there is a better flow here.

The article for reference: https://joebirch.co/2020/02/21/exploring-the-android-11-developer-preview-permission-changes/

**Comment by hotchemi** [comment]
@mannodermaus Thx! I've gone through the article and my takeaways was,


- One of the neat things about Android 11 is that if a user selects “Deny” within a specific permission dialog more than once, then that will be treated as “Don’t ask again“. This means that applications that frequently ask for permissions that users do not accept will be defaulted to not being able to ask for those permissions again, which is a huge win for user privacy.
- When targeting Android 11, applications will no longer have the ability to request access to location data all of the time from within your application – this option has been removed from the in-app permissions dialog. If an application wants permission to access the users location all the time when in the background, the permission will need to be granted from within the system settings screen for your application.

Now checking more on https://developer.android.com/preview/privacy

**Comment by hotchemi** [comment]
Let me close the issue.

**Comment by tayyabejaz** [comment]
@hotchemi Have you added the Location Permission in the library? 

PS I am using version 3.1.0
