### ISSUE TITLE
how to user in androidX fragment?i can't   find  generate RuntimePermissions,but  activity  can.  version4.6.0

### ISSUE THREAD

**Issue by MrYang12** [permissions-dispatcher/PermissionsDispatcher#666]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by hotchemi** [comment]
@MrYang12 could you elaborate more? have you checked your fragment is annotated with RuntimePermissions annotation?

**Comment by xx-xiaobai** [comment]
android x fragment中不能使用，会弹框提示是否为react

**Comment by hotchemi** [comment]
Let me close the issue as no response for a while.
