### ISSUE TITLE
"withPermissionsCheck()" doesn't work omitted callback parameters

### ISSUE THREAD

**Issue by TentaShion** [permissions-dispatcher/PermissionsDispatcher#668]
## Overview
Thank you develop permissions-dispatcher-ktx.
I tried using 1.0.0-alpha2, it seems not to work "withPermissionsCheck()".
If add default action for these parameters, I'm very happy!

``` kotlin
WebViewBuilder()
    .geolocationEnabled(true)
    .javaScriptEnabled(true)
    .onGeolocationPermissionsShowPrompt { origin, callback ->
        withPermissionsCheck(Manifest.permission.ACCESS_FINE_LOCATION) {
            callback?.invoke(origin, true, false)
        }
    }
    .into(findViewById<WebView>(R.id.webview_target))
    .loadUrl("https://www.google.co.jp/maps")
```

* If omit "onShowRationale" parameter, it don't show a permissions dialog.
→ If add "onShowRationale", it show dialog.
* If omit "onPermissionDenied" parameter and dialog result is "denied", it seems not to fire denied action.
→ "Never Ask" is same.

### Expected
I hope behavior  like a "PermissionsDispatcher 4.3.0".

### Actual
If omit these parameters, it seems not to work permission dialog.

* onNeverAskAgain
* onPermissionDenied
* onShowRationale

### Development
* Android 10 Emulator
* Android Studio 3.6.2

### Library
* [permissionsdispatcher-ktx 1.0.0-alpha2](https://bintray.com/hotchemi/org.permissionsdispatcher/permissionsdispatcher-ktx/1.0.0-alpha2)

## Reproducible steps
It can reproduce using [ktx-sample](https://github.com/permissions-dispatcher/PermissionsDispatcher/tree/master/ktx-sample) too.
Please try omitting callback parameters.

**Comment by hotchemi** [comment]
Thank you so much! I was packed today gonna take a look tomorrow!

**Comment by hotchemi** [comment]
Sorry for the late, the issue has been addressed in https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/678 and beta1 is available now! Thank you for the feedback~
