### ISSUE TITLE
Why your project's lint rules don't work

### ISSUE THREAD

**Issue by Edward-going** [permissions-dispatcher/PermissionsDispatcher#669]
Obviously, your project integrates the lint framework, lint lintaar, but they don't work in smaple app

**Comment by hotchemi** [comment]
Thx, this is weird.

**Comment by Edward-going** [comment]
Do you know the cause of the problem？I'm also solving similar problems on other projects

**Comment by hotchemi** [comment]
^ Tried again and seems now it works.
