### ISSUE TITLE
Hope the anonymous function 'Func' in TypeAliasesKt can add params

### ISSUE THREAD

**Issue by Gslullaby** [permissions-dispatcher/PermissionsDispatcher#671]
We may need permissions that be denied by user to do some extra work. So, I hope the PermissionsRequestFragment's field 'onNeverAskAgain' and 'onPermissionDenied' can  return the denied permissions back.   

Related Code:
```kotlin
internal typealias Func = () -> Unit    
```

```kotlin
override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == this.requestCode) {
            if (verifyPermissions(*grantResults)) {
                requiresPermission?.invoke()
            } else {
                if (!PermissionUtils.shouldShowRequestPermissionRationale(this, *permissions)) {
                    onNeverAskAgain?.invoke()
                } else {
                    onPermissionDenied?.invoke()
                }
            }
        }
        dismiss()
    }

**Comment by hotchemi** [comment]
in my understanding you can easily detect which permission is denied because you explicitly set to a certain`withPermissionsCheck` as an argument right?

**Comment by LiPengW** [comment]
@hotchemi Yes, but i think we can get denied permissions while ```verifyPermissions``` called, then return it by ```onNeverAskAgain``` or  ```onPermissionDenied```.
May be more reasonable

**Comment by hotchemi** [comment]
@LiPengW Could you elaborate why it's `reasonable and convenient` if you're seriously proposing the idea? we have not provided the hint even in stable version and we have not got such kind of feedback so.
https://github.com/permissions-dispatcher/PermissionsDispatcher#1-attach-annotations

**Comment by LiPengW** [comment]
@hotchemi From my (a ktx lib user) point of view. It is lib's responsablity to tell me Which permissons i applied has be denied, rather than verify by myself.
If you don't think so ,i just close it

**Comment by hotchemi** [comment]
Thank you and sorry for the late. After glancing overall your proposal might make sense and let try to come up with a new API interface later on with taking it into account!

**Comment by Gslullaby** [comment]
@hotchemi thx
