### ISSUE TITLE
Digging into Kotlin Symbol Processing API

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#674]
Not sure it'd be next standard or so but we may be able to improve build-time performance.

https://github.com/android/kotlin/tree/ksp/libraries/tools/kotlin-symbol-processing-api

**Comment by hotchemi** [comment]
let me close the issue as we've invented ktx module and don't have to rely on code generation anymore!

**Comment by aniketbhoite** [comment]
I was hoping to learn ksp from the project but I might have to do it the other way around. I'll try
