### ISSUE TITLE
Why not return a permissions: array < out string > in the method of onpermissiondenied annotation to indicate the permission set rejected

### ISSUE THREAD

**Issue by Edward-going** [permissions-dispatcher/PermissionsDispatcher#675]
Why not return a permissions: array < out string > in the method of onpermissiondenied annotation to indicate the permission set rejected

**Comment by hotchemi** [comment]
Could you elaborate more why you claimed that and what's the benefit we can obtain then?

**Comment by hotchemi** [comment]
let me close the issue due to a lack of supplementary info.
