### ISSUE TITLE
Shows lint "NeedOnRequestPermissionsResult" when not using braces to call generated method

### ISSUE THREAD

**Issue by ashishmahla** [permissions-dispatcher/PermissionsDispatcher#680]
The following implementation shows lint error. Changing function implementation to use braces doesn't throw that lint.

```
override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) = onRequestPermissionsResult(requestCode, grantResults)
```

This is a valid call and should not throw the lint error.

**Comment by hotchemi** [comment]
thank you for the report. let us check.

**Comment by mannodermaus** [comment]
I wonder if the Lint rule trips over the explicit return type of `Unit` when the method is written like an assignment. 🤔
