### ISSUE TITLE
Is there a member function for PermissionRequest class to never ask again ?

### ISSUE THREAD

**Issue by ramseth001** [permissions-dispatcher/PermissionsDispatcher#694]
In the @OnShowRationale annotation method, we have a default parameter object **request: PermissionRequest**.

This object has two methods: Allow and Deny. I am just wondering whether you have any plans to add "NeverAskAgain" method in the future, or there is a similar type of method ?

```
new AlertDialog.Builder(this)
                .setPositiveButton("ALLOW", (dialogInterface, i) -> request.proceed())
                .setNegativeButton("DENY", (dialogInterface, i) -> request.cancel())
                .setCancelable(false)
                .setMessage(rationaleText)
                .show();
```

I just thought it would be useful if there is a third method like **request.neverAskAgain()**.

**Comment by ramseth001** [comment]
![Uploading device-2020-11-13-094657.png…]()

**Comment by ramseth001** [comment]
![device-2020-11-13-094657](https://user-images.githubusercontent.com/19702328/99029217-f378c600-2597-11eb-8746-185a11e1323e.png)

**Comment by hotchemi** [comment]
@ramseth001 the option `neverAskAgain` is automatically added if the user has denied the permission request and we can't select we should add the option or not. Does that make sense?

**Comment by ramseth001** [comment]
@hotchemi I understand it. Just wanted to make sure whether there is any way to achieve it.
