### ISSUE TITLE
startActivity onResume it will infinite loop

### ISSUE THREAD

**Issue by zdxiang** [permissions-dispatcher/PermissionsDispatcher#696]
First , I had use PermissionCheck onStart, 
when I startActivity onResuem, it will loop.
The activity is a empty activity. I need to start it onResume。

 #90 I have check many times,  not suitable for my situation

**Comment by hotchemi** [comment]
>  startActivity onResuem

I wonder this is not our library's issue? could you elaborate more with pseudo code?

**Comment by zdxiang** [comment]
Just like this:    
override fun onResume() {
        super.onResume()
        val intent = Intent(this, Just4TestActivity::class.java)
        startActivity(intent)
    }

**Comment by hotchemi** [comment]
seems like https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/696#issuecomment-731900971 is not related to the library. let me close the issue.
