### ISSUE TITLE
@RuntimePermissions和@NeedsPermission都加了，但是还是报错啊

### ISSUE THREAD

**Issue by zhouxu88** [permissions-dispatcher/PermissionsDispatcher#698]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by mannodermaus** [comment]
Please rephrase your question in English and adhere to the issue format of this repository. Feel free to reopen the ticket afterwards!
