### ISSUE TITLE
[KTX] System dialog doesn't show up, after manually disable permission from setting

### ISSUE THREAD

**Issue by TurKurT656** [permissions-dispatcher/PermissionsDispatcher#705]
## Overview

I've two permissions in my fragment (camera and storage) this is my code for them:

```
private fun checkCameraPermission() {
        constructPermissionsRequest(
                Manifest.permission.CAMERA,
                onShowRationale = { request ->
                    showPermissionRationaleDialog(
                            Manifest.permission.CAMERA,
                            onAccept = { request.proceed() },
                            onDeny = { navigateHome() }
                    )
                },
                onPermissionDenied = {
                    navigateHome()
                },
                onNeverAskAgain = {
                    showPermissionNeverAskAgainDialog(
                            Manifest.permission.CAMERA,
                            onDeny = { navigateHome() }
                    )
                }
        ) {
            showCamera()
        }.launch()
    }

    private fun checkStoragePermission() {
        constructPermissionsRequest(
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                onShowRationale = { request ->
                    showPermissionRationaleDialog(
                        Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        onAccept = { request.proceed() }
                    )
                },
                onNeverAskAgain = {
                    showPermissionNeverAskAgainDialog(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                }
        ) {
            saveFile()
        }.launch()
    }
```
I'm calling `checkCameraPermission()` on my fragment's `onStart()` function. but there is a save button for calling `checkStoragePermission()`. Everything works great. until when I go to setting and manually disable storage permission from there. After returning to the fragment when I press the save button, Rationale shows up but when I accept button the system permission dialog doesn't show up. (I set a breakpoint and I saw that `request.proceed()` called. but It doesn't jump to the `requiresPermission` method.)
The Strange part is that If I disable `checkCameraPermission()` from `onStart()` It will work.

### Expected

System dialog shows up event after manually disabling permission from setting

### Actual

 System dialog doesn't show up, after manually disable permission from setting (when there is two permission checks on the fragment)

## Environment

- Which library version are you using? ktx 1.0.1
- On which devices do you observe the issue? all devices

**Comment by TurKurT656** [comment]
I will be glad if someone give me a temporary solution

**Comment by hotchemi** [comment]
@TurKurT656 Hi sorry for the late I am back from the vacation. would you mind trying to call `constructPermissionsRequest` only in onCreate or something?

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/3a238dad5a27d90b0bf27f22be920a2d6ac968a8/ktx-sample/src/main/java/permissions/dispatcher/ktx/sample/MainFragment.kt#L18-L31

**Comment by hotchemi** [comment]
Admittedly this is a bit counter-intuitive, but Google official way has the same restriction and we're unifying an interface..we might need lint to detect it.

https://developer.android.com/reference/androidx/activity/result/ActivityResultCaller#registerForActivityResult(androidx.activity.result.contract.ActivityResultContract%3CI,%20O%3E,%20androidx.activity.result.ActivityResultCallback%3CO%3E)

**Comment by TurKurT656** [comment]
I've tried `onAttach()` and `onCreate()` too. None of them worked for me. Also I've to use this inside `onstart()` method because I need to check camera permission every time fragment resumed and resume camera if the permission granted.

**Comment by hotchemi** [comment]
um, let us take a look at this weekend 🙏

**Comment by hotchemi** [comment]
I tried with ktx-sample but could not repro on API level Q. Which env did you try?
https://imgur.com/a/9oCLAyK

**Comment by TurKurT656** [comment]
I'm using api level 29. I'll try to make a sample project and share it with you.

**Comment by xie438305665** [comment]
Encountered the same problem      And appeared  FragmentManager is already executing transactions

**Comment by kenshin171** [comment]
encountered the same issue with permissionsRequester.launch() in `onStart` and initialization of `permissionsRequester` in `onAttach(Context)` in a fragment.

```
                         E  java.lang.IllegalStateException: FragmentManager is already executing transactions
                         E      at androidx.fragment.app.FragmentManager.ensureExecReady(SourceFile:1790)
                         E      at androidx.fragment.app.FragmentManager.execSingleAction(SourceFile:1826)
                         E      at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(SourceFile:303)
                         E      at permissions.dispatcher.ktx.PermissionsRequesterImpl$launch$requestFun$1.invoke(SourceFile:30)
                         E      at permissions.dispatcher.ktx.PermissionsRequesterImpl$launch$requestFun$1.invoke(SourceFile:7)
                         E      at permissions.dispatcher.ktx.PermissionsRequesterImpl.launch(SourceFile:35)
                         E      at a.b.fragment.myFragment.onStart(SourceFile:355)
... omitted ...
```

**Comment by hotchemi** [comment]
thx, let me take  a look again 🙏

**Comment by hotchemi** [comment]
um, testing on API level 28~30 but haven't been able to repro the issue 🤔 If someone could prepare an example that can repro the issue that'd be awesome 🙏 

But for `java.lang.IllegalStateException: FragmentManager is already executing transactions` I assume we can replace `` commitNowAllowingStateLoss` with `executePendingTransactions`.

**Comment by hotchemi** [comment]
I assume [ktx-1.0.2](https://search.maven.org/artifact/com.github.permissions-dispatcher/ktx/1.0.2/aar) has resolved the issue 🙏

**Comment by hotchemi** [comment]
@xie438305665 @kenshin171 @TurKurT656 https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/705#issuecomment-789107946 and please reopen the issue as appropriate 🙇

**Comment by kenshin171** [comment]
> I assume [ktx-1.0.2](https://search.maven.org/artifact/com.github.permissions-dispatcher/ktx/1.0.2/aar) has resolved the issue 🙏

it seems 1.0.2 relies on `4.9.0-SNAPSHOT`

**Comment by hotchemi** [comment]
good catch and sorry for messing up after maven central 🙏 now released 1.0.3 and updated readme 🙇

**Comment by kenshin171** [comment]
@hotchemi  just tried ktx 1.0.3, crash is not happening anymore. Just a suggestion, or maybe even a nitpick.

Maybe should only create `requestFun` when `PermissionUtils.shouldShowRequestPermissionRationale(activity, *permissions) == false` ?

like below 

```kotlin
override fun launch() {
        if (permissionRequestType.checkPermissions(activity, permissions)) {
            requiresPermission()
        } else {
            ViewModelProvider(activity).get(PermissionRequestViewModel::class.java).observe(
                activity,
                requiresPermission,
                onPermissionDenied,
                onNeverAskAgain
            )
            
            if (PermissionUtils.shouldShowRequestPermissionRationale(activity, *permissions)) {
                onShowRationale?.invoke(KtxPermissionRequest.create(onPermissionDenied, requestFun))
            } else {
               val requestFun: Fun = {
                    activity.supportFragmentManager
                        .beginTransaction()
                        .replace(android.R.id.content, permissionRequestType.fragment(permissions))
                        .commitAllowingStateLoss()
                }
                requestFun.invoke()
            }
        }
    }
```

And excuse my ignorance if i cannot figure out the reason, but maybe for fragments, could use `childfragmentmanager`(as u mentioned before) and fragment scope viewmodels instead? It looks more correct to encapsulate the permissions request to the fragment scope itself instead of the activity scope if the permissions is request from the fragment.

like below


```kotlin
override fun launch() {
        if (permissionRequestType.checkPermissions(activity, permissions)) {
            requiresPermission()
        } else {
            ViewModelProvider(activity).get(PermissionRequestViewModel::class.java).observe(
                fragment,
                requiresPermission,
                onPermissionDenied,
                onNeverAskAgain
            )
            
            if (PermissionUtils.shouldShowRequestPermissionRationale(activity, *permissions)) {
                onShowRationale?.invoke(KtxPermissionRequest.create(onPermissionDenied, requestFun))
            } else {
               val requestFun: Fun = {
                    fragment.childFragmentManager
                        .beginTransaction()
                        .replace(android.R.id.content, permissionRequestType.fragment(permissions))
                        .commitAllowingStateLoss()
                }
                requestFun.invoke()
            }
        }
    }
```

**Comment by hotchemi** [comment]
thx for the suggestion, let me check!

**Comment by kenshin171** [comment]
@hotchemi any updates on this? 

1) storing a reference to `PermissionRequest` in `PermissionRequester`
2) using childfragmentmanager and a fragment scope viewmodel

**Comment by hotchemi** [comment]
@kenshin171 sorry for the late,

> Maybe should only create requestFun when PermissionUtils.shouldShowRequestPermissionRationale(activity, *permissions) == false ?

LGTM. would you mind creating PR?

> storing a reference to PermissionRequest in PermissionRequester

do you have any proposal for this? for now I'm not so much positive as it looks beyond the responsibility of the library but might be because I haven't been able to imagine that well.


> using childfragmentmanager and a fragment scope viewmodel

Actually when I was trying to fix the original issue, the initial approach was to use childfragmentmanager, but it didn't go well(sorry I forgot why but might be avoidable).

**Comment by kenshin171** [comment]
@hotchemi 

ok i have tried to implement some changes and found out

> > Maybe should only create requestFun when PermissionUtils.shouldShowRequestPermissionRationale(activity, *permissions) == false ?

this is not valid anymore i missed out 
```onShowRationale?.invoke(KtxPermissionRequest.create(onPermissionDenied, requestFun))```
is also using the `requestFun`, no change needed here.

> 
> > storing a reference to PermissionRequest in PermissionRequester
> 
> do you have any proposal for this? for now I'm not so much positive as it looks beyond the responsibility of the library but might be because I haven't been able to imagine that well.
> 

I was basically trying to find a way to implement orientation change support, which did not work as the permissionRequest relies on higher order functions that were passed as arguments to the permissionsRequester which is no longer valid in an orientation change even if i saved the permissionRequest object in the viewmodel. 

And due to these higher order function arguments, the ktx lib will not work for orientation change scnario. Annotation will still work though as no higher order function are being used as arguments.

> > using childfragmentmanager and a fragment scope viewmodel
> 
> Actually when I was trying to fix the original issue, the initial approach was to use childfragmentmanager, but it didn't go well(sorry I forgot why but might be avoidable).

and the childfragmentmanager is not possible due to this
```No view found for id 0x1020002 (android:id/content) for fragment NormalRequestPermissionFragment{69f2b36 #0 id=0x1020002}```
There is not container to inflate the permission fragment in the childfragmentmanager.

**Comment by hotchemi** [comment]
got it for point 1 and 3.
for point 2, let me think it over...it may have some degrades from my initial design 🤔
