### ISSUE TITLE
Host artifact elsewhere - JCenter shuts down on May

### ISSUE THREAD

**Issue by alvindizon** [permissions-dispatcher/PermissionsDispatcher#706]
Don't know if you've seen this but JCenter is shutting down on May: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Maybe now is the time to migrate the artifact to somewhere else?

**Comment by hotchemi** [comment]
Thx, I was about to open the same issue! we're gonna do that ASAP.

**Comment by hotchemi** [comment]
Almost done with https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/708.
Accidentally pushed wrong ktx version and ordering removal on https://issues.sonatype.org/browse/OSSRH-64137 lol

**Comment by hotchemi** [comment]
unfortunately, we can't remove publish artefact from maven central.. 🤔 let me go with it.
added migration guide: https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/709
