### ISSUE TITLE
Wrong behaviour of ktx library when two premissions are requested in one screen

### ISSUE THREAD

**Issue by DzmitryLakisau** [permissions-dispatcher/PermissionsDispatcher#717]
Sample code can be found here: https://github.com/DzmitryLakisau/Permissions-Dispatcher-KTX-Bug

Wrong action is called after granting second permission.

Steps to reproduce:
1. Press "Open camera".
2. Grant camera permission. 
3. Camera is opened. Close it.
4. Press "Open file manager".
5. Grant storage permission.
6. Camera is opened again.

After this, if press "Open file manager" again right action will be called.
This issue is absent in annotation version of library.

**Comment by hotchemi** [comment]
thx, let us take a look

**Comment by hotchemi** [comment]
we've addressed the issue in 1.0.4. thx for the report! 🙏
