### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by flobizDipen** [permissions-dispatcher/PermissionsDispatcher#721]
##Description

- Getting illegal state exception
`
Fatal Exception: java.lang.IllegalStateException: Fragment not attached to an activity.
       at androidx.fragment.app.Fragment.requireActivity(Fragment.java:833)
       at com.packageName.FragmentPermissionsDispatcher.functionWithPermissionCheck(FragmentPermissionsDispatcher.java:33)
`

This is happening because `hasSelfPermissions` requires activity context and for that, you guys are using `requireActivity()`
which can be null too

`@NonNull
    public final FragmentActivity requireActivity() {
        FragmentActivity activity = getActivity();
        if (activity == null) {
            throw new IllegalStateException("Fragment " + this + " not attached to an activity.");
        }
        return activity;
    }`

## Environment

- Which library version are you using? - 4.6.0
- On which devices do you observe the issue? - Many Device and almost every Android Version

**Comment by hotchemi** [comment]
thx for the report.
But I'm afraid you should avoid calling `functionWithPermissionCheck` when activity could be null because then we can't do anything(`PermissionChecker.checkSelfPermission` requires context and we eventually need activity or context).

**Comment by rq973017553** [comment]
please use "by lazy" in your fragment
private val showCamera by lazy {
        constructPermissionsRequest(
            permissions = arrayOf(Manifest.permission.CAMERA,
                Manifest.permission.WRITE_EXTERNAL_STORAGE
            ),
               onShowRationale = ::onCameraShowRationale,
               onPermissionDenied = ::onCameraDenied,
               onNeverAskAgain = ::onCameraNeverAskAgain
        ) {
            startActivity(Intent(mActivity, XXXX::class.java))
        }
    }
