### ISSUE TITLE
JCenter is scheduled for closing

### ISSUE THREAD

**Issue by tommus** [permissions-dispatcher/PermissionsDispatcher#725]
## Overview

- JCenter Maven repository is scheduled for closing. Migrate to other central repository.
- JCenter end of life memo - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

### Expected

- Since Gradle 7.0 JCenter Maven repository is marked as deprecated. Library should remain available even though developer will decide to drop JCenter support.

### Actual

- Removing JCenter from project repositories will result of PermissionsDispatcher library being unable to find.

## Environment

- Only library 4.3.0 is available from different repo than JCenter. Since then multiple versions have been released.
- The problem is connected to build system. It's not device-related.

## Reproducible steps

- Add latest PermissionsDispatcher version to the project.
- Having JCenter still in repository list, synchronize the project.
- At this point everything should be fine.
- Remove JCenter from repository list.
- Synchronize the project (optionally purging local Maven repository).
- Gradle synchronization will fail with "Could not resolve all files" error mentioning PermissionsDispatcher library.

**Comment by hotchemi** [comment]
@tommus simply..we've done? https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md#migrating-to-maven-central

**Comment by hotchemi** [comment]
> Removing JCenter from project repositories will result of PermissionsDispatcher library being unable to find.

This is something we can do but should be done after JCenter's actual closing.
