### ISSUE TITLE
Is PermissionsDispatcher going to migrate to Kotlin Symbol Processing API

### ISSUE THREAD

**Issue by aniketbhoite** [permissions-dispatcher/PermissionsDispatcher#726]
Is PermissionsDispatcher going to migrate to [Kotlin Symbol Processing API](https://github.com/google/ksp)? or provide an option with it?
If so approximately when?

**Comment by hotchemi** [comment]
Unfortunately it's not our focus for now but it's good to have it :D Would you mind sending PR?
https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/674
