### ISSUE TITLE
Wrong visibility of generated functions under kotlin 1.5.0, generated classes won't compile.

### ISSUE THREAD

**Issue by bgeradz** [permissions-dispatcher/PermissionsDispatcher#727]
Prerequisites:
- permisson-dispatcher 4.7 or 4.8
- kotlin 1.5
- activity class with ```internal```  visibility.

Generated MainActivityPermissionDispatcher.kt class generates ```public``` methods like
```fun MainActivity.internalInitWithPermissionCheck()```

leading to errors like
```
/app/build/generated/source/kapt/debug/com/example/newapp/MainActivityPermissionsDispatcher.kt: (17, 5): 'public' member exposes its 'internal' receiver type MainActivity
```

Switching back to kotlin 1.4.30 - the generated functions become ```internal```, everything works

**Comment by bgeradz** [comment]
Here is a fresh project created with latest AndroidStudio with minimum PermissionDispatcher code to manifest the issue.
[NewApp.zip](https://github.com/permissions-dispatcher/PermissionsDispatcher/files/6443226/NewApp.zip)

**Comment by hotchemi** [comment]
thx for the report, we need to fix this issue!

**Comment by hotchemi** [comment]
Sorry for the late, 4.9.1 has been released.
