### ISSUE TITLE
401 from public repository

### ISSUE THREAD

**Issue by kamilj** [permissions-dispatcher/PermissionsDispatcher#728]
No jetpack privileges

Could not GET 'https://jitpack.io/com/github/hotchemi/permissionsdispatcher-processor/4.8.0/permissionsdispatcher-processor-4.8.0.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

**Comment by kamilj** [comment]
Ok wrong address
Addres has changed
from
com.github.hotchemi:permissionsdispatcher
to
org.permissionsdispatcher:permissionsdispatcher

**Comment by hotchemi** [comment]
Yup, see https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md#migrating-to-maven-central as well.
