### ISSUE TITLE
permissionRequest proceed doesn't work due to KtxPermissionRequest.requestPermission being null

### ISSUE THREAD

**Issue by SamYStudiO** [permissions-dispatcher/PermissionsDispatcher#734]
## Overview
- When `onLocationShowRationale` get called and i want to proceed `permissionRequest`, system permission dialog is not showing up.

## Environment
PermissionsDispatcher KTX

This doesn't work cause  `KtxPermissionRequest.requestPermission` weakreference got lost and is null
```
 private fun onLocationShowRationale(permissionRequest: PermissionRequest) {
        findNavController().navigate(
            RoundFormFragmentDirections.actionGlobalAlertDialog(
                messageRes = R.string.NSLocationWhenInUseUsageDescription,
                negativeButtonRes = R.string.global_cancel,
                positiveButtonRes = R.string.dialog_gps_permissions_activate,
                requestCode = REQUEST_CODE_PERMISSION_RATIONAL
            )
        )
        setDialogPositiveClickListener {requestCode, _ ->
            when (requestCode) {
                REQUEST_CODE_PERMISSION_RATIONAL -> {
                    permissionRequest.proceed()
                }
            }
        }
        setDialogNegativeClickListener {requestCode, _ ->
            when (requestCode) {
                REQUEST_CODE_PERMISSION_RATIONAL -> {
                    permissionRequest.cancel()
                    findNavController().popBackStack()
                }
            }
        }
    }
```

But this works
```
 private fun onLocationShowRationale(permissionRequest: PermissionRequest) {
        permissionRequest.proceed()
    }
```

Any help appreciated
Thx!

**Comment by SamYStudiO** [comment]
I guess this func is being garbage collected since nobody keep a reference, so if you delay your `permissionRequest.proceed()` then it may be null
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/c8876729dfd3cd2158d57098e56e02514792fd62/ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt#L27-L32

**Comment by hotchemi** [comment]
@SamYStudiO thx, could you give us more info for this case? in my understanding this could happen when `PermissionsRequester` instance is already released from memory?

**Comment by SamYStudiO** [comment]
@hotchemi hello
exactly there seems  to have nothing keeping a reference to `requestFun` specified in my previous answer. so if you delay ` permissionRequest.proceed()` with a confirmation dialog for example, that function may have been garbage collected when effectively calling `proceed.`

**Comment by hotchemi** [comment]
@SamYStudiO thx, one thing I haven't understood is in your case `PermissionsRequester` is also destroyed? If so I'm wondering we should not keep a reference to functions, otherwise, it causes the memory leak again in theory 🤔 
in ktx-sample, it works as expected and do you think we can do a similar approach?

https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/af245e244ddb11c7656f6a66ae8b3c89412bbcb3/ktx-sample/src/main/java/permissions/dispatcher/ktx/sample/MainFragment.kt#L82-L83

**Comment by SamYStudiO** [comment]
I'm not sure why ktx-sample works, i guess for this one GC hasn't been done yet, in my case
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/c8876729dfd3cd2158d57098e56e02514792fd62/ktx/src/main/java/permissions/dispatcher/ktx/KtxPermissionRequest.kt#L11
`requestPermission.get()` is null if i delay it with my custom dialog implementation and wait my dialog to return a positive value

**Comment by hotchemi** [comment]
can we get an example that we can repro the issue?
The reason ktx-sample works is `requestPermission` and `permissionDenied` are still referenced from `PermissionsRequester` AFAIK.

**Comment by SamYStudiO** [comment]
it's a huge projet, i may have a look to extract, but i'm pretty sure problem is `requestFun` having no strong reference anywhere and so beeing destroy before we may use it
https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/c8876729dfd3cd2158d57098e56e02514792fd62/ktx/src/main/java/permissions/dispatcher/ktx/PermissionsRequesterImpl.kt#L27-L32

**Comment by hotchemi** [comment]
tried https://github.com/permissions-dispatcher/PermissionsDispatcher/compare/prototype/gc_for_PermissionRequest?expand=1 but PermissionRequest worked as expected.
My advice here is to keep `PermissionsRequester` alive until everything related to permission handling is finished. this is out expected use case for the API.

**Comment by SamYStudiO** [comment]
Hello
check ktx-sample from my fork to reproduce the pb
https://github.com/SamYStudiO/PermissionsDispatcher
Issue is reproductible when using DialogFragment instead of AlertDialog directly

**Comment by hotchemi** [comment]
thx, I'll take a look

**Comment by hotchemi** [comment]
I tried your repo but could not repro the issue, unfortunately.. 🤔 
could you give more environment info? I tried on Nexus5 API level 30 emulator.

<img src="https://user-images.githubusercontent.com/471318/129060674-d8c4db30-eec1-4714-b3aa-13583dfd6d03.gif" width="250" />

**Comment by hotchemi** [comment]
thx, I suppose https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/742 would resolve the issue.

**Comment by hotchemi** [comment]
ktx-1.1.2 has been released.
