### ISSUE TITLE
Cannot generate classes after switching to maven

### ISSUE THREAD

**Issue by torkmandukk** [permissions-dispatcher/PermissionsDispatcher#747]
Everything worked fine on jcenter version 4.8.0, but after switching to maven library version 4.8.0, no classes were generated. I also tried 4.9.1, of course, with the same results.

**Comment by hotchemi** [comment]
What's the error message you've got? JFYI: https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md#migrating-to-maven-central

**Comment by hotchemi** [comment]
Let me know if you still have the issue.

**Comment by torkmandukk** [comment]
It's fixed, thank you.
