### ISSUE TITLE
StartAtyPermissionsDispatcher.permissionsSuccessWithPermissionCheck(StartAty.this);没反应

### ISSUE THREAD

**Issue by wuh876** [permissions-dispatcher/PermissionsDispatcher#751]
没反应怎么回事呢

**Comment by hotchemi** [comment]
Sorry, could you elaborate in English?

**Comment by wuh876** [comment]
No response. What's going on

**Comment by hotchemi** [comment]
Could you **elaborate** the problem? we don't know `StartAtyPermissionsDispatcher` and related code.

**Comment by wuh876** [comment]
PermissionsDispatcher.WithPermissionCheck(this),no response
can not open system  permission request

**Comment by wuh876** [comment]
some  huawei phone

**Comment by hotchemi** [comment]
Could you check our sample module works on your environment or give us an adequate example we can repro the issue?
