### ISSUE TITLE
Execution failed for task ':app:kaptDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution    > java.lang.reflect.InvocationTargetException (no error message)

### ISSUE THREAD

**Issue by wangfeigit** [permissions-dispatcher/PermissionsDispatcher#752]
]Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by hotchemi** [comment]
seems dup of https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/753, let us close.
