### ISSUE TITLE
Execution failed for task ':app:kaptDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution    > java.lang.reflect.InvocationTargetException (no error message)

### ISSUE THREAD

**Issue by wangfeigit** [permissions-dispatcher/PermissionsDispatcher#753]
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by ArmChilingarov** [comment]
Try to change the functions annotated with @NeedPermission to "public".

**Comment by hotchemi** [comment]
This might be related to kapt itself, not the lib itself 🤔 
@wangfeigit still have the issue?

**Comment by hotchemi** [comment]
Let us close the issue.
