### ISSUE TITLE
Ktx-1.1.4

### ISSUE THREAD

**Issue by enriquebautista** [permissions-dispatcher/PermissionsDispatcher#769]
Hi! how we can use ktx-1.1.4? to solve many issues in Android 12

**Comment by hotchemi** [comment]
Sorry for the late, doesn't `implementation 'com.github.permissions-dispatcher:ktx:1.1.4'` work for you? 👀 
ref: https://search.maven.org/artifact/com.github.permissions-dispatcher/ktx/1.1.4/aar
